defmodule Tend.Store do
  @moduledoc """
  The persistence layer: the only module that touches SQL.

  A port of `internal/store`, built up in parts: opening the file and getting
  the schema onto it, then the flat task surface on top of that. Nothing calls
  either yet -- the CLI commands that would are a later phase.

  Built on the raw `Exqlite.Sqlite3` API rather than Ecto. The Go store is
  hand-written SQL against a schema that two binaries have to agree on
  byte for byte, and a port is a port: an Ecto schema per table would be a
  redesign wearing a port's clothes, and `Ecto.Migration` cannot express the
  goose files at all.

  ## Where the SQL comes from

  Go's queries are generated by sqlc from `internal/store/queries/*.sql`, and
  there is no Elixir counterpart to lean on, so every statement here is
  written inline as a module attribute -- copied **textually** from the
  like-named constant in `internal/store/gen/*.sql.go` so a reviewer can diff
  the two. Where a copy had to change, a comment above it says why; today
  there is exactly one such place (`@set_task_state`).

  Rows come back from those statements as plain lists and are turned into
  domain structs by `Tend.Store.Row`, the port of the mappers at the bottom of
  `store.go`.

  ## The pragmas are load-bearing

  `open/1` sets the same three the Go DSN does (`dsnFor` in
  `internal/store/store.go`):

    * `journal_mode = WAL`, so a reader in one process and a writer in another
      do not block each other -- the TUI, `tend add` from a shell, an MCP tool
      call and a workflow runner are routinely all live at once.
    * `busy_timeout = 5000`, so a briefly contended write waits instead of
      failing.
    * `foreign_keys = ON`, so the schema's cascades actually fire. Several
      migrations are written on the assumption that they do.

  A connection that skipped them would still work, right up until it silently
  did not, so they are asserted in the tests rather than trusted.
  """

  alias Exqlite.Sqlite3
  alias Tend.Store.Migrator
  alias Tend.Store.Row
  alias Tend.Store.Watcher
  alias Tend.Task
  alias Tend.Task.ChildCount
  alias Tend.Task.Priority
  alias Tend.Task.Project
  alias Tend.Task.SessionStatus
  alias Tend.Task.State
  alias Tend.Workflow.RunState

  @typedoc """
  An open store: the connection, and the path it was opened on.

  The path is kept for the same reason `store.Store` keeps its DSN -- the
  change watcher opens a second handle on the same file.
  """
  @type t :: %__MODULE__{conn: Sqlite3.db(), path: String.t()}

  defstruct [:conn, :path]

  @doc """
  Opens the database at `path`, creating it and its parent directory if
  needed, and brings the schema up to date.

  Idempotent: opening a database that is already current runs no migration.

  Errors come back as `{:error, reason}` with a descriptive term, and every
  one of them is a `t:Tend.Error.t/0`: `Tend.Error.message/1` renders
  `:db_directory_failed`, `:db_open_failed`, `:pragma_failed`,
  `:migration_failed` and `:query_failed`.
  """
  @spec open(String.t()) :: {:ok, t()} | {:error, term()}
  def open(path) do
    with :ok <- ensure_directory(path),
         {:ok, conn} <- open_connection(path) do
      case Migrator.migrate(conn) do
        :ok ->
          {:ok, %__MODULE__{conn: conn, path: path}}

        {:error, reason} ->
          Sqlite3.close(conn)
          {:error, reason}
      end
    end
  end

  @doc """
  Opens a connection on `path` with the pragmas above and nothing else: no
  directory creation, no migration ladder.

  This is the Elixir counterpart of Go's `dsnFor` -- the one place the pragma
  set is written down, shared by `open/1` and by the change watcher, whose
  pinned connection has to be configured exactly like a store's but must never
  migrate. Everything else should go through `open/1`.
  """
  @spec open_connection(String.t()) :: {:ok, Sqlite3.db()} | {:error, term()}
  def open_connection(path) do
    with {:ok, conn} <- connect(path) do
      case pragmas(conn) do
        :ok ->
          {:ok, conn}

        {:error, reason} ->
          Sqlite3.close(conn)
          {:error, reason}
      end
    end
  end

  @doc """
  Starts a `Tend.Store.Watcher` on the file this store was opened on.

  The port of Go's `(*Store).Watch`. The watcher gets its own connection, so
  it shares nothing with this one and neither closing ends the other; `opts`
  are `Tend.Store.Watcher.start_link/1`'s, minus `:path`.

  Nothing in the port calls this yet -- there is no UI to reload.
  """
  @spec watch(t(), keyword()) :: GenServer.on_start()
  def watch(%__MODULE__{path: path}, opts \\ []) do
    opts |> Keyword.put(:path, path) |> Watcher.start_link()
  end

  @doc """
  Closes the underlying connection.
  """
  @spec close(t()) :: :ok | {:error, term()}
  def close(%__MODULE__{conn: conn}), do: Sqlite3.close(conn)

  # -- the copied statements -------------------------------------------------
  #
  # Each of these is the body of the like-named constant in
  # `internal/store/gen/*.sql.go`, verbatim.

  @create_task """
  INSERT INTO tasks (title, project_id)
  VALUES (?, ?)
  RETURNING id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  """

  @create_task_with_body """
  INSERT INTO tasks (title, body_md, project_id)
  VALUES (?, ?, ?)
  RETURNING id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  """

  @get_task """
  SELECT id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  FROM tasks
  WHERE id = ?
  """

  @list_live_tasks """
  SELECT t.id, t.title, t.body_md, t.state, t.parent_id, t.priority, t.due, t.snooze_until, t.created_at, t.updated_at, t.completed_at, t.project_id
  FROM tasks t
  JOIN states s ON s.name = t.state
  WHERE s.is_terminal = 0
    AND s.hidden_by_default = 0
    AND (t.snooze_until IS NULL OR t.snooze_until <= date('now'))
    AND (?1 IS NULL OR t.project_id = ?1)
  ORDER BY s.sort_order, t.priority IS NULL, t.priority, t.id
  """

  @list_live_with_completed_tasks """
  SELECT t.id, t.title, t.body_md, t.state, t.parent_id, t.priority, t.due, t.snooze_until, t.created_at, t.updated_at, t.completed_at, t.project_id
  FROM tasks t
  JOIN states s ON s.name = t.state
  WHERE (s.is_terminal = 0 OR t.state = 'done' OR s.hidden_by_default = 1)
    AND (t.snooze_until IS NULL OR t.snooze_until <= date('now'))
    AND (?1 IS NULL OR t.project_id = ?1)
  ORDER BY s.sort_order, t.priority IS NULL, t.priority, t.id
  """

  @list_inbox_tasks """
  SELECT t.id, t.title, t.body_md, t.state, t.parent_id, t.priority, t.due, t.snooze_until, t.created_at, t.updated_at, t.completed_at, t.project_id
  FROM tasks t
  WHERE t.state = 'inbox'
    AND t.parent_id IS NULL
    AND (?1 IS NULL OR t.project_id = ?1)
  ORDER BY t.id
  """

  @list_project_tasks """
  SELECT id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  FROM tasks
  WHERE project_id = ?
  ORDER BY id
  """

  @count_inbox_tasks """
  SELECT COUNT(*)
  FROM tasks t
  WHERE t.state = 'inbox'
    AND t.parent_id IS NULL
    AND (?1 IS NULL OR t.project_id = ?1)
  """

  @list_child_counts """
  SELECT parent_id,
         COUNT(*)                                                   AS total,
         CAST(SUM(CASE WHEN state = 'done' THEN 1 ELSE 0 END) AS INTEGER) AS done
  FROM tasks
  WHERE parent_id IS NOT NULL
  GROUP BY parent_id
  """

  @list_session_statuses """
  SELECT task_id, status
  FROM agent_sessions
  ORDER BY last_active_at ASC, id ASC
  """

  @list_active_runs """
  SELECT id, workflow_id, task_id, cwd, state, current_step_run_id, tmux_session, started_at, ended_at, error
  FROM workflow_runs
  WHERE state NOT IN ('done', 'failed', 'cancelled')
  ORDER BY started_at DESC, id DESC
  """

  # The generated constant opens with a stray `;` and two blank lines -- the
  # terminator of the query declared before it in `queries/tasks.sql`, which
  # sqlc folded into this one's text. It is dropped here because
  # `sqlite3_prepare` compiles the *first* statement it is handed and an empty
  # one compiles to nothing at all. Everything from `UPDATE` on is verbatim.
  @set_task_state """
  UPDATE tasks
  SET state        = ?1,
      completed_at = CASE WHEN ?1 = 'done' THEN datetime('now') ELSE NULL END,
      updated_at   = datetime('now')
  WHERE id = ?2
  """

  @set_task_priority """
  UPDATE tasks
  SET priority   = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_task_due """
  UPDATE tasks
  SET due        = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_task_title """
  UPDATE tasks
  SET title      = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_task_body """
  UPDATE tasks
  SET body_md    = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @append_task_body """
  UPDATE tasks
  SET body_md    = CASE
                     WHEN trim(body_md, ' ' || char(9, 10, 13)) = '' THEN ?1
                     ELSE rtrim(body_md, ' ' || char(9, 10, 13)) || char(10, 10) || ?1
                   END,
      updated_at = datetime('now')
  WHERE id = ?2
  """

  @delete_task """
  DELETE FROM tasks
  WHERE id = ?
  """

  # -- capture ---------------------------------------------------------------

  @doc """
  Captures a task into the default project: a bare title, everything else
  defaulted by the schema (state `:inbox`, empty body).

  Deliberately not "the active project". A capture with no project named lands
  somewhere fixed and predictable, so `tend add` from any shell behaves the
  same way every time; callers that know where a task belongs say so through
  `add_task_in/3`. This is `AGENTS.md` §2 -- capture requires nothing,
  organization is a later, separate act -- applied to the project as well as
  to the state.
  """
  @spec add_task(t(), String.t()) :: {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task(store, title), do: add_task_in(store, Project.default_id(), title)

  @doc """
  Captures a task into a named project, for `tend add -p` and the TUI's
  quick-add against the selected project.
  """
  @spec add_task_in(t(), integer(), String.t()) :: {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task_in(store, project_id, title) when is_integer(project_id) do
    with {:ok, normalized} <- Task.normalize_title(title) do
      insert_task(store, @create_task, [normalized, project_id])
    end
  end

  @doc """
  Captures a task that arrives with context already attached (an imported Jira
  ticket, say): title plus a markdown body, everything else defaulted by the
  schema.
  """
  @spec add_task_with_body(t(), String.t(), String.t()) ::
          {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task_with_body(store, title, body) do
    add_task_with_body_in(store, Project.default_id(), title, body)
  end

  @doc """
  `add_task_with_body/3` against an explicit project.
  """
  @spec add_task_with_body_in(t(), integer(), String.t(), String.t()) ::
          {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task_with_body_in(store, project_id, title, body)
      when is_integer(project_id) and is_binary(body) do
    with {:ok, normalized} <- Task.normalize_title(title) do
      insert_task(store, @create_task_with_body, [normalized, body, project_id])
    end
  end

  # -- reads -----------------------------------------------------------------

  @doc """
  Loads one task by id.

  A task that is not there is `{:error, {:task_not_found, id}}`. Go has no
  `ErrTaskNotFound`: its `GetTask` wraps whatever `database/sql` returned, and
  a missing row arrives as `sql.ErrNoRows`. exqlite has no such error -- an
  empty result is an empty list -- so the port has to name the condition
  itself rather than let "no rows" and "the query failed" read alike.
  """
  @spec get_task(t(), integer()) :: {:ok, Task.t()} | {:error, Tend.Error.t()}
  def get_task(store, id) when is_integer(id) do
    case query(store, @get_task, [id], "loading task #{id}") do
      {:ok, [row]} -> Row.to_task(row)
      {:ok, []} -> {:error, {:task_not_found, id}}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  The live view: non-terminal, non-hidden states, and not snoozed into the
  future.

  `nil` for `project_id` means every project (the projects column's All row);
  otherwise the view is scoped to that one.
  """
  @spec list_live(t(), integer() | nil) :: {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_live(store, project_id) do
    with {:ok, rows} <-
           query(store, @list_live_tasks, [project_filter(project_id)], "listing live tasks") do
      Row.to_tasks(rows)
    end
  end

  @doc """
  `list_live/2` plus the completed (`:done`) tasks and the hidden-by-default
  states (`:someday`), for when the list view has the completed section
  toggled on. Snoozed tasks stay out either way.
  """
  @spec list_live_with_completed(t(), integer() | nil) ::
          {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_live_with_completed(store, project_id) do
    with {:ok, rows} <-
           query(
             store,
             @list_live_with_completed_tasks,
             [project_filter(project_id)],
             "listing live tasks with completed"
           ) do
      Row.to_tasks(rows)
    end
  end

  @doc """
  Every task still in the `:inbox` state, oldest first. This feeds the triage
  view.
  """
  @spec list_inbox(t(), integer() | nil) :: {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_inbox(store, project_id) do
    with {:ok, rows} <-
           query(store, @list_inbox_tasks, [project_filter(project_id)], "listing inbox tasks") do
      Row.to_tasks(rows)
    end
  end

  @doc """
  Every task in a project, at any depth and in any state, oldest first.

  It feeds the move-to-parent picker, which needs the whole tree rather than
  the scoped live view.
  """
  @spec list_project_tasks(t(), integer()) :: {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_project_tasks(store, project_id) when is_integer(project_id) do
    with {:ok, rows} <-
           query(
             store,
             @list_project_tasks,
             [project_id],
             "listing tasks in project #{project_id}"
           ) do
      Row.to_tasks(rows)
    end
  end

  @doc """
  The number of tasks awaiting triage.
  """
  @spec count_inbox(t(), integer() | nil) :: {:ok, integer()} | {:error, Tend.Error.t()}
  def count_inbox(store, project_id) do
    case query(store, @count_inbox_tasks, [project_filter(project_id)], "counting inbox tasks") do
      {:ok, [[count]]} -> {:ok, count}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Per-parent sub-task done/total counts, for every task that has children.

  Done children are filtered out of the live view, so the list derives its N/M
  progress from this instead. A childless task is absent from the map rather
  than present with zeroes.
  """
  @spec child_counts(t()) :: {:ok, %{integer() => ChildCount.t()}} | {:error, Tend.Error.t()}
  def child_counts(store) do
    with {:ok, rows} <- query(store, @list_child_counts, [], "listing child counts") do
      counts =
        for [parent_id, total, done] <- rows, parent_id != nil, into: %{} do
          {parent_id, %ChildCount{done: done, total: total}}
        end

      {:ok, counts}
    end
  end

  @doc """
  Each task's agent status, keyed by task id -- what the list row renders so a
  background session's state is visible without opening the task.

  A task with a workflow run in a non-terminal state takes the run's state,
  mapped into the session vocabulary (`Tend.Workflow.RunState.session_status/1`):
  a headless run has no tmux pane for the poller to classify and its step
  sessions are `:starting` for most of their life, so the run row is the
  better signal. The one exception is a paused run, which yields to the task's
  latest session status when there is one -- during a takeover the interactive
  session's own hooks say more than "paused" does -- and reads `:idle` only
  when the task has no session at all. A task with only ended runs falls
  through to its sessions.

  The session query returns every session oldest-first and the map keeps the
  last write per task, which is the most recent one. That is cheaper to reason
  about than a correlated `MAX()` subquery and needs no tiebreak rule for two
  sessions sharing a timestamp, since the ordering already falls back to id.
  Active runs come newest-first, so the first run seen per task is the one
  that wins.
  """
  @spec session_statuses(t()) ::
          {:ok, %{integer() => SessionStatus.t()}} | {:error, Tend.Error.t()}
  def session_statuses(store) do
    with {:ok, session_rows} <-
           query(store, @list_session_statuses, [], "listing session statuses"),
         {:ok, run_rows} <- query(store, @list_active_runs, [], "listing active runs") do
      statuses =
        for [task_id, status] <- session_rows, into: %{} do
          {task_id, SessionStatus.parse(status)}
        end

      {:ok, overlay_runs(run_rows, statuses)}
    end
  end

  # -- mutators --------------------------------------------------------------

  @doc """
  Moves a task to a new workflow state. Entering `:done` stamps
  `completed_at`; entering any other state clears it.
  """
  @spec set_state(t(), integer(), State.t()) :: :ok | {:error, Tend.Error.t()}
  def set_state(store, id, state) when is_integer(id) do
    if State.valid?(state) do
      execute(
        store,
        @set_task_state,
        [State.format(state), id],
        "setting task #{id} state to #{state}"
      )
    else
      {:error, {:unknown_state, to_string(state)}}
    end
  end

  @doc """
  Assigns a priority (1 = highest .. 4) to a task; `nil` clears it.
  """
  @spec set_priority(t(), integer(), Priority.t() | nil) :: :ok | {:error, Tend.Error.t()}
  def set_priority(store, id, priority) when is_integer(id) do
    if priority == nil or Priority.valid?(priority) do
      execute(store, @set_task_priority, [priority, id], "setting task #{id} priority")
    else
      {:error, {:priority_out_of_range, priority}}
    end
  end

  @doc """
  Assigns a due date (ISO 8601, validated) to a task; `nil` clears it.
  """
  @spec set_due(t(), integer(), String.t() | nil) :: :ok | {:error, Tend.Error.t()}
  def set_due(store, id, due) when is_integer(id) do
    with {:ok, normalized} <- normalize_due(due) do
      execute(store, @set_task_due, [normalized, id], "setting task #{id} due date")
    end
  end

  @doc """
  Renames a task; the new title is trimmed and blanks rejected, the same
  validation capture uses.
  """
  @spec set_title(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def set_title(store, id, title) when is_integer(id) do
    with {:ok, normalized} <- Task.normalize_title(title) do
      execute(store, @set_task_title, [normalized, id], "setting task #{id} title")
    end
  end

  @doc """
  Replaces a task's markdown body.
  """
  @spec set_body(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def set_body(store, id, body) when is_integer(id) and is_binary(body) do
    execute(store, @set_task_body, [body, id], "setting task #{id} body")
  end

  @doc """
  Adds text to the end of a task's markdown body as a new paragraph: an empty
  body simply becomes the text, otherwise a blank line separates the existing
  body from it.

  Empty or whitespace-only text is a no-op, so callers cannot leave stray
  blank lines behind. The append itself happens in SQL, so it is atomic
  against a concurrent writer.
  """
  @spec append_body(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def append_body(store, id, text) when is_integer(id) and is_binary(text) do
    if String.trim(text) == "" do
      :ok
    else
      execute(store, @append_task_body, [text, id], "appending to task #{id} body")
    end
  end

  @doc """
  Removes a task. Its sub-tasks cascade away with it (the `parent_id` foreign
  key is `ON DELETE CASCADE`), and the `task_events` trigger logs one
  `deleted` row per task that went.

  Deleting an id that is not there is not an error, exactly as Go's is not:
  the statement matches no rows and the generated `:exec` method discards the
  row count.
  """
  @spec delete_task(t(), integer()) :: :ok | {:error, Tend.Error.t()}
  def delete_task(store, id) when is_integer(id) do
    execute(store, @delete_task, [id], "deleting task #{id}")
  end

  # -- transactions ----------------------------------------------------------

  @doc """
  Runs `fun` inside a transaction, committing its result and rolling back on
  `{:error, reason}`.

  The port of `inTx` in `internal/store/projects.go`, and public for the same
  reason Go's is package-wide: every multi-statement invariant in the store
  goes through it. `tasks.project_id` carries no foreign key (see migration
  00007), so the writes that stand in for one have to be atomic themselves.

  Go's helper takes a `func(q *gen.Queries) error` and hands it a `Queries`
  bound to the transaction. exqlite has no such object -- a transaction is a
  property of the connection, not a handle -- so `fun` is handed the store
  itself and simply calls the ordinary functions on it.

  A raise, a throw or an exit inside `fun` rolls back and is re-raised
  unchanged, which is what Go's `defer tx.Rollback()` buys it: the store's
  connection is long-lived, so a transaction left open by an unwinding caller
  would block every later write on it.

  Nothing in the task surface is multi-statement, so this has no caller on
  this branch; the functions that need it -- `SetProject`, `SetParent`,
  `SetTags`, `DeleteProject` -- are later parts of the store port.
  """
  @spec transaction(t(), (t() -> result)) :: result | {:error, Tend.Error.t()} when result: var
  def transaction(%__MODULE__{} = store, fun) when is_function(fun, 1) do
    with :ok <- statement(store, "BEGIN", "beginning transaction") do
      try do
        case fun.(store) do
          {:error, reason} ->
            rollback(store)
            {:error, reason}

          result ->
            case statement(store, "COMMIT", "committing transaction") do
              :ok -> result
              {:error, reason} -> {:error, rollback_and(store, reason)}
            end
        end
      catch
        kind, reason ->
          rollback(store)
          :erlang.raise(kind, reason, __STACKTRACE__)
      end
    end
  end

  defp ensure_directory(path) do
    case path |> Path.dirname() |> File.mkdir_p() do
      :ok -> :ok
      {:error, reason} -> {:error, {:db_directory_failed, Path.dirname(path), reason}}
    end
  end

  defp connect(path) do
    case Sqlite3.open(path) do
      {:ok, conn} -> {:ok, conn}
      {:error, reason} -> {:error, {:db_open_failed, path, reason}}
    end
  end

  defp pragmas(conn) do
    Enum.reduce_while(
      [
        "PRAGMA journal_mode = WAL",
        "PRAGMA busy_timeout = 5000",
        "PRAGMA foreign_keys = ON"
      ],
      :ok,
      fn sql, :ok ->
        case Sqlite3.execute(conn, sql) do
          :ok -> {:cont, :ok}
          {:error, reason} -> {:halt, {:error, {:pragma_failed, sql, reason}}}
        end
      end
    )
  end

  # The port of Go's projectFilter. sqlc's nullable named argument becomes an
  # untyped interface{} there, so nil means "every project" and a bare int64
  # scopes the query; exqlite binds nil as SQL NULL and an integer as itself,
  # which is the same two cases against the same `?1 IS NULL OR ...` clause.
  # The guard is the point: without it a project id of the wrong shape would
  # bind as something `?1 IS NULL` reads as present, quietly scoping the query
  # to nothing rather than failing.
  defp project_filter(nil), do: nil
  defp project_filter(id) when is_integer(id), do: id

  # `INSERT ... RETURNING` yields exactly one row. Anything else means the
  # statement above stopped being the insert it is copied from, which is worth
  # an error rather than a match failure three frames away.
  defp insert_task(store, sql, params) do
    case query(store, sql, params, "inserting task") do
      {:ok, [row]} -> Row.to_task(row)
      {:ok, rows} -> {:error, {:query_failed, "inserting task", {:rows_returned, length(rows)}}}
      {:error, reason} -> {:error, reason}
    end
  end

  defp normalize_due(nil), do: {:ok, nil}
  defp normalize_due(due) when is_binary(due), do: Task.normalize_date(due)

  # Best effort, exactly as Go's `defer func() { _ = tx.Rollback() }()` is: the
  # caller is already getting the real failure, and a rollback that itself
  # fails has nothing better to say. After a successful COMMIT it is a no-op
  # error ("cannot rollback - no transaction is active"), which is why the
  # result is discarded rather than reported.
  defp rollback(store) do
    _ = statement(store, "ROLLBACK", "rolling back transaction")
    :ok
  end

  defp rollback_and(store, reason) do
    rollback(store)
    reason
  end

  # The second half of SessionStatuses: the active runs, newest-first, laid
  # over the per-task session statuses. `seen` is Go's `fromRun` map.
  defp overlay_runs(rows, statuses) do
    {statuses, _seen} = Enum.reduce(rows, {statuses, MapSet.new()}, &overlay_run/2)
    statuses
  end

  # Go reads r.State off a gen.WorkflowRun as a raw string and hands it to
  # workflow.RunState(r.State).SessionStatus(), which answers for any value.
  # RunState.parse/1 is strict, so a state the schema's CHECK does not allow
  # lands on the same "says nothing" answer a terminal one does -- and, like a
  # terminal one, does not claim the task either, so an older active run still
  # gets its turn.
  defp overlay_run(row, {statuses, seen} = unchanged) do
    [_id, _workflow_id, task_id, _cwd, state | _rest] = row

    with false <- MapSet.member?(seen, task_id),
         {:ok, run_state} <- RunState.parse(state),
         {:ok, status} <- RunState.session_status(run_state) do
      # A paused run claims the task either way, but yields its own status to
      # the task's session when there is one: during a takeover the
      # interactive session's hooks say more than "paused" does.
      if run_state == :paused and Map.has_key?(statuses, task_id) do
        {statuses, MapSet.put(seen, task_id)}
      else
        {Map.put(statuses, task_id, status), MapSet.put(seen, task_id)}
      end
    else
      # Already spoken for by a newer run, or a run whose state has no status.
      _skip -> unchanged
    end
  end

  # Runs a statement for effect. Go's generated :exec methods discard the
  # sql.Result, and so does this: not one caller in the task surface looks at
  # the row count.
  defp execute(store, sql, params, context) do
    with {:ok, _rows} <- query(store, sql, params, context), do: :ok
  end

  # Prepare, bind, run, release. The statement is released on both paths --
  # exqlite hands back a NIF resource, and leaking one holds the compiled
  # statement (and its read transaction) open.
  defp query(%__MODULE__{conn: conn}, sql, params, context) do
    case Sqlite3.prepare(conn, sql) do
      {:ok, statement} ->
        result =
          with :ok <- Sqlite3.bind(statement, params) do
            Sqlite3.fetch_all(conn, statement)
          end

        Sqlite3.release(conn, statement)
        tag(result, context)

      {:error, reason} ->
        {:error, {:query_failed, context, reason}}
    end
  end

  # BEGIN/COMMIT/ROLLBACK take no parameters and return no rows, so they go
  # through sqlite3_exec the way the migrator's statements do.
  defp statement(%__MODULE__{conn: conn}, sql, context) do
    case Sqlite3.execute(conn, sql) do
      :ok -> :ok
      {:error, reason} -> {:error, {:query_failed, context, reason}}
    end
  end

  # Every driver failure is wrapped with the label its Go call site passes to
  # fmt.Errorf, so the two trees' messages read the same.
  defp tag({:ok, rows}, _context), do: {:ok, rows}
  defp tag({:error, reason}, context), do: {:error, {:query_failed, context, reason}}
end
