defmodule Tend.Store do
  @moduledoc """
  The persistence layer: the only module that touches SQL.

  A port of `internal/store`, built up in parts: opening the file and getting
  the schema onto it, the flat task surface on top of that, then the workflow
  definition rows and the agent-session and tmux-session surface. Nothing calls
  any of it yet -- the CLI commands, MCP tools and TUI views that would are
  later phases.

  Built on the raw `Exqlite.Sqlite3` API rather than Ecto. The Go store is
  hand-written SQL against a schema that two binaries have to agree on
  byte for byte, and a port is a port: an Ecto schema per table would be a
  redesign wearing a port's clothes, and `Ecto.Migration` cannot express the
  goose files at all.

  ## Where the SQL comes from

  Go's queries are generated by sqlc from `internal/store/queries/*.sql`, and
  there is no Elixir counterpart to lean on, so every statement here is
  written inline as a module attribute -- copied **textually** from the
  like-named constant in `internal/store/gen/*.sql.go` so a reviewer can diff
  the two. Where a copy had to change, a comment above it says why; today
  there is exactly one such place (`@set_task_state`).

  Rows come back from those statements as plain lists and are turned into
  domain structs by `Tend.Store.Row`, the port of the mappers at the bottom of
  `store.go`.

  ## The pragmas are load-bearing

  `open/1` sets the same three the Go DSN does (`dsnFor` in
  `internal/store/store.go`):

    * `journal_mode = WAL`, so a reader in one process and a writer in another
      do not block each other -- the TUI, `tend add` from a shell, an MCP tool
      call and a workflow runner are routinely all live at once.
    * `busy_timeout = 5000`, so a briefly contended write waits instead of
      failing.
    * `foreign_keys = ON`, so the schema's cascades actually fire. Several
      migrations are written on the assumption that they do.

  A connection that skipped them would still work, right up until it silently
  did not, so they are asserted in the tests rather than trusted.
  """

  alias Exqlite.Sqlite3
  alias Tend.Store.Migrator
  alias Tend.Store.Row
  alias Tend.Store.Watcher
  alias Tend.Task
  alias Tend.Task.ChildCount
  alias Tend.Task.Priority
  alias Tend.Task.Project
  alias Tend.Task.Session
  alias Tend.Task.SessionStatus
  alias Tend.Task.State
  alias Tend.Task.TaskSession
  alias Tend.Workflow
  alias Tend.Workflow.RunState

  @typedoc """
  An open store: the connection, and the path it was opened on.

  The path is kept for the same reason `store.Store` keeps its DSN -- the
  change watcher opens a second handle on the same file.
  """
  @type t :: %__MODULE__{conn: Sqlite3.db(), path: String.t()}

  defstruct [:conn, :path]

  @doc """
  Opens the database at `path`, creating it and its parent directory if
  needed, and brings the schema up to date.

  Idempotent: opening a database that is already current runs no migration.

  Errors come back as `{:error, reason}` with a descriptive term, and every
  one of them is a `t:Tend.Error.t/0`: `Tend.Error.message/1` renders
  `:db_directory_failed`, `:db_open_failed`, `:pragma_failed`,
  `:migration_failed` and `:query_failed`.
  """
  @spec open(String.t()) :: {:ok, t()} | {:error, term()}
  def open(path) do
    with :ok <- ensure_directory(path),
         {:ok, conn} <- open_connection(path) do
      case Migrator.migrate(conn) do
        :ok ->
          {:ok, %__MODULE__{conn: conn, path: path}}

        {:error, reason} ->
          Sqlite3.close(conn)
          {:error, reason}
      end
    end
  end

  @doc """
  Opens a connection on `path` with the pragmas above and nothing else: no
  directory creation, no migration ladder.

  This is the Elixir counterpart of Go's `dsnFor` -- the one place the pragma
  set is written down, shared by `open/1` and by the change watcher, whose
  pinned connection has to be configured exactly like a store's but must never
  migrate. Everything else should go through `open/1`.
  """
  @spec open_connection(String.t()) :: {:ok, Sqlite3.db()} | {:error, term()}
  def open_connection(path) do
    with {:ok, conn} <- connect(path) do
      case pragmas(conn) do
        :ok ->
          {:ok, conn}

        {:error, reason} ->
          Sqlite3.close(conn)
          {:error, reason}
      end
    end
  end

  @doc """
  Starts a `Tend.Store.Watcher` on the file this store was opened on.

  The port of Go's `(*Store).Watch`. The watcher gets its own connection, so
  it shares nothing with this one and neither closing ends the other; `opts`
  are `Tend.Store.Watcher.start_link/1`'s, minus `:path`.

  Nothing in the port calls this yet -- there is no UI to reload.
  """
  @spec watch(t(), keyword()) :: GenServer.on_start()
  def watch(%__MODULE__{path: path}, opts \\ []) do
    opts |> Keyword.put(:path, path) |> Watcher.start_link()
  end

  @doc """
  Closes the underlying connection.
  """
  @spec close(t()) :: :ok | {:error, term()}
  def close(%__MODULE__{conn: conn}), do: Sqlite3.close(conn)

  # -- the copied statements -------------------------------------------------
  #
  # Each of these is the body of the like-named constant in
  # `internal/store/gen/*.sql.go`, verbatim.

  @create_task """
  INSERT INTO tasks (title, project_id)
  VALUES (?, ?)
  RETURNING id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  """

  @create_task_with_body """
  INSERT INTO tasks (title, body_md, project_id)
  VALUES (?, ?, ?)
  RETURNING id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  """

  @get_task """
  SELECT id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  FROM tasks
  WHERE id = ?
  """

  @list_live_tasks """
  SELECT t.id, t.title, t.body_md, t.state, t.parent_id, t.priority, t.due, t.snooze_until, t.created_at, t.updated_at, t.completed_at, t.project_id
  FROM tasks t
  JOIN states s ON s.name = t.state
  WHERE s.is_terminal = 0
    AND s.hidden_by_default = 0
    AND (t.snooze_until IS NULL OR t.snooze_until <= date('now'))
    AND (?1 IS NULL OR t.project_id = ?1)
  ORDER BY s.sort_order, t.priority IS NULL, t.priority, t.id
  """

  @list_live_with_completed_tasks """
  SELECT t.id, t.title, t.body_md, t.state, t.parent_id, t.priority, t.due, t.snooze_until, t.created_at, t.updated_at, t.completed_at, t.project_id
  FROM tasks t
  JOIN states s ON s.name = t.state
  WHERE (s.is_terminal = 0 OR t.state = 'done' OR s.hidden_by_default = 1)
    AND (t.snooze_until IS NULL OR t.snooze_until <= date('now'))
    AND (?1 IS NULL OR t.project_id = ?1)
  ORDER BY s.sort_order, t.priority IS NULL, t.priority, t.id
  """

  @list_inbox_tasks """
  SELECT t.id, t.title, t.body_md, t.state, t.parent_id, t.priority, t.due, t.snooze_until, t.created_at, t.updated_at, t.completed_at, t.project_id
  FROM tasks t
  WHERE t.state = 'inbox'
    AND t.parent_id IS NULL
    AND (?1 IS NULL OR t.project_id = ?1)
  ORDER BY t.id
  """

  @list_project_tasks """
  SELECT id, title, body_md, state, parent_id, priority, due, snooze_until, created_at, updated_at, completed_at, project_id
  FROM tasks
  WHERE project_id = ?
  ORDER BY id
  """

  @count_inbox_tasks """
  SELECT COUNT(*)
  FROM tasks t
  WHERE t.state = 'inbox'
    AND t.parent_id IS NULL
    AND (?1 IS NULL OR t.project_id = ?1)
  """

  @list_child_counts """
  SELECT parent_id,
         COUNT(*)                                                   AS total,
         CAST(SUM(CASE WHEN state = 'done' THEN 1 ELSE 0 END) AS INTEGER) AS done
  FROM tasks
  WHERE parent_id IS NOT NULL
  GROUP BY parent_id
  """

  @list_session_statuses """
  SELECT task_id, status
  FROM agent_sessions
  ORDER BY last_active_at ASC, id ASC
  """

  @list_active_runs """
  SELECT id, workflow_id, task_id, cwd, state, current_step_run_id, tmux_session, started_at, ended_at, error
  FROM workflow_runs
  WHERE state NOT IN ('done', 'failed', 'cancelled')
  ORDER BY started_at DESC, id DESC
  """

  # The generated constant opens with a stray `;` and two blank lines -- the
  # terminator of the query declared before it in `queries/tasks.sql`, which
  # sqlc folded into this one's text. It is dropped here because
  # `sqlite3_prepare` compiles the *first* statement it is handed and an empty
  # one compiles to nothing at all. Everything from `UPDATE` on is verbatim.
  @set_task_state """
  UPDATE tasks
  SET state        = ?1,
      completed_at = CASE WHEN ?1 = 'done' THEN datetime('now') ELSE NULL END,
      updated_at   = datetime('now')
  WHERE id = ?2
  """

  @set_task_priority """
  UPDATE tasks
  SET priority   = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_task_due """
  UPDATE tasks
  SET due        = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_task_title """
  UPDATE tasks
  SET title      = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_task_body """
  UPDATE tasks
  SET body_md    = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @append_task_body """
  UPDATE tasks
  SET body_md    = CASE
                     WHEN trim(body_md, ' ' || char(9, 10, 13)) = '' THEN ?1
                     ELSE rtrim(body_md, ' ' || char(9, 10, 13)) || char(10, 10) || ?1
                   END,
      updated_at = datetime('now')
  WHERE id = ?2
  """

  @delete_task """
  DELETE FROM tasks
  WHERE id = ?
  """

  @create_workflow """
  INSERT INTO workflows (name, description)
  VALUES (?, ?)
  RETURNING id, name, description, created_at, updated_at
  """

  @get_workflow """
  SELECT id, name, description, created_at, updated_at
  FROM workflows
  WHERE id = ?
  """

  @get_workflow_by_name """
  SELECT id, name, description, created_at, updated_at
  FROM workflows
  WHERE name = ?
  """

  @list_workflows """
  SELECT w.id, w.name, w.description, w.created_at, w.updated_at,
         COALESCE(c.n, 0) AS step_count
  FROM workflows w
  LEFT JOIN (
    SELECT workflow_id, COUNT(*) AS n
    FROM workflow_steps
    GROUP BY workflow_id
  ) c ON c.workflow_id = w.id
  ORDER BY w.name
  """

  @rename_workflow """
  UPDATE workflows
  SET name       = ?,
      updated_at = datetime('now')
  WHERE id = ?
  """

  @set_workflow_description """
  UPDATE workflows
  SET description = ?,
      updated_at  = datetime('now')
  WHERE id = ?
  """

  @delete_workflow """
  DELETE FROM workflows
  WHERE id = ?
  """

  @list_active_run_ids_for_workflow """
  SELECT id
  FROM workflow_runs
  WHERE workflow_id = ?
    AND state NOT IN ('done', 'failed', 'cancelled')
  ORDER BY id
  """

  # The four below belong to the step and edge surface, which is a later part
  # of the store port (`AddStep`, `ListSteps`, `SetEdge`, `ListEdges`). They
  # are here now because `duplicate_workflow/3` is the one workflow-row
  # function with real logic and it copies rows of both tables -- exactly as
  # Go's DuplicateWorkflow reaches past its own section for ListSteps,
  # CreateStepFull, ListEdgesForWorkflow and UpsertEdge.

  @list_steps """
  SELECT id, workflow_id, name, kind, prompt_md, model, permission_mode, sort_order, created_at, updated_at
  FROM workflow_steps
  WHERE workflow_id = ?
  ORDER BY sort_order, id
  """

  @create_step_full """
  INSERT INTO workflow_steps (workflow_id, name, kind, prompt_md, model, permission_mode, sort_order)
  VALUES (?, ?, ?, ?, ?, ?, ?)
  RETURNING id, workflow_id, name, kind, prompt_md, model, permission_mode, sort_order, created_at, updated_at
  """

  @list_edges_for_workflow """
  SELECT e.id, e.from_step_id, e.outcome, e.to_step_id, e.max_iterations
  FROM workflow_edges e
  JOIN workflow_steps s ON s.id = e.from_step_id
  WHERE s.workflow_id = ?
  ORDER BY s.sort_order, s.id, e.outcome
  """

  @upsert_edge """
  INSERT INTO workflow_edges (from_step_id, outcome, to_step_id, max_iterations)
  VALUES (?, ?, ?, ?)
  ON CONFLICT(from_step_id, outcome) DO UPDATE
  SET to_step_id     = excluded.to_step_id,
      max_iterations = excluded.max_iterations
  RETURNING id, from_step_id, outcome, to_step_id, max_iterations
  """

  @create_session """
  INSERT INTO agent_sessions (task_id, external_id, cwd, label, tmux_session, workflow_step_run_id, status, status_updated_at)
  VALUES (?, ?, ?, ?, ?, ?, 'starting', strftime('%Y-%m-%d %H:%M:%f', 'now'))
  RETURNING id, task_id, external_id, cwd, label, started_at, last_active_at, tmux_session, needs_recap, status, status_updated_at, workflow_step_run_id
  """

  @delete_session """
  DELETE FROM agent_sessions
  WHERE id = ?
  """

  @list_sessions_for_task """
  SELECT id, task_id, external_id, cwd, label, started_at, last_active_at, tmux_session, needs_recap, status, status_updated_at, workflow_step_run_id
  FROM agent_sessions
  WHERE task_id = ?
  ORDER BY last_active_at DESC, id DESC
  """

  @list_sessions_for_project """
  SELECT s.id, s.task_id, s.external_id, s.cwd, s.label, s.started_at, s.last_active_at, s.tmux_session, s.needs_recap, s.status, s.status_updated_at, s.workflow_step_run_id, t.title AS task_title, t.state AS task_state
  FROM agent_sessions s
  JOIN tasks t ON t.id = s.task_id
  WHERE (?1 IS NULL OR t.project_id = ?1)
  ORDER BY s.last_active_at DESC, s.id DESC
  """

  @touch_session """
  UPDATE agent_sessions
  SET last_active_at = datetime('now')
  WHERE id = ?
  """

  @update_session_label """
  UPDATE agent_sessions
  SET label = ?
  WHERE external_id = ?
  """

  @set_session_needs_recap """
  UPDATE agent_sessions
  SET needs_recap = ?
  WHERE external_id = ?
  """

  @set_session_status """
  UPDATE agent_sessions
  SET status = ?, status_updated_at = strftime('%Y-%m-%d %H:%M:%f', 'now'), last_active_at = datetime('now')
  WHERE external_id = ?
  """

  @list_sessions_needing_recap """
  SELECT id, task_id, external_id, cwd, label, started_at, last_active_at, tmux_session, needs_recap, status, status_updated_at, workflow_step_run_id
  FROM agent_sessions
  WHERE needs_recap = 1
  ORDER BY last_active_at DESC, id DESC
  """

  @claim_session_recap """
  UPDATE agent_sessions
  SET needs_recap = 0
  WHERE external_id = ? AND needs_recap = 1
  """

  @list_sessions_with_tmux """
  SELECT id, task_id, external_id, cwd, label, started_at, last_active_at, tmux_session, needs_recap, status, status_updated_at, workflow_step_run_id
  FROM agent_sessions
  WHERE tmux_session != '' AND status != 'ended'
  ORDER BY last_active_at DESC, id DESC
  """

  @set_session_working_if_unchanged """
  UPDATE agent_sessions
  SET status = 'working', status_updated_at = strftime('%Y-%m-%d %H:%M:%f', 'now')
  WHERE external_id = ? AND status_updated_at IS ?
  """

  @set_session_idle_if_unchanged """
  UPDATE agent_sessions
  SET status = 'idle', status_updated_at = strftime('%Y-%m-%d %H:%M:%f', 'now')
  WHERE external_id = ? AND status_updated_at IS ?
  """

  @set_session_ended_if_unchanged """
  UPDATE agent_sessions
  SET status = 'ended', status_updated_at = strftime('%Y-%m-%d %H:%M:%f', 'now')
  WHERE external_id = ? AND status_updated_at IS ?
  """

  # -- capture ---------------------------------------------------------------

  @doc """
  Captures a task into the default project: a bare title, everything else
  defaulted by the schema (state `:inbox`, empty body).

  Deliberately not "the active project". A capture with no project named lands
  somewhere fixed and predictable, so `tend add` from any shell behaves the
  same way every time; callers that know where a task belongs say so through
  `add_task_in/3`. This is `AGENTS.md` §2 -- capture requires nothing,
  organization is a later, separate act -- applied to the project as well as
  to the state.
  """
  @spec add_task(t(), String.t()) :: {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task(store, title), do: add_task_in(store, Project.default_id(), title)

  @doc """
  Captures a task into a named project, for `tend add -p` and the TUI's
  quick-add against the selected project.
  """
  @spec add_task_in(t(), integer(), String.t()) :: {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task_in(store, project_id, title) when is_integer(project_id) do
    with {:ok, normalized} <- Task.normalize_title(title) do
      insert_task(store, @create_task, [normalized, project_id])
    end
  end

  @doc """
  Captures a task that arrives with context already attached (an imported Jira
  ticket, say): title plus a markdown body, everything else defaulted by the
  schema.
  """
  @spec add_task_with_body(t(), String.t(), String.t()) ::
          {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task_with_body(store, title, body) do
    add_task_with_body_in(store, Project.default_id(), title, body)
  end

  @doc """
  `add_task_with_body/3` against an explicit project.
  """
  @spec add_task_with_body_in(t(), integer(), String.t(), String.t()) ::
          {:ok, Task.t()} | {:error, Tend.Error.t()}
  def add_task_with_body_in(store, project_id, title, body)
      when is_integer(project_id) and is_binary(body) do
    with {:ok, normalized} <- Task.normalize_title(title) do
      insert_task(store, @create_task_with_body, [normalized, body, project_id])
    end
  end

  # -- reads -----------------------------------------------------------------

  @doc """
  Loads one task by id.

  A task that is not there is `{:error, {:task_not_found, id}}`. Go has no
  `ErrTaskNotFound`: its `GetTask` wraps whatever `database/sql` returned, and
  a missing row arrives as `sql.ErrNoRows`. exqlite has no such error -- an
  empty result is an empty list -- so the port has to name the condition
  itself rather than let "no rows" and "the query failed" read alike.
  """
  @spec get_task(t(), integer()) :: {:ok, Task.t()} | {:error, Tend.Error.t()}
  def get_task(store, id) when is_integer(id) do
    case query(store, @get_task, [id], "loading task #{id}") do
      {:ok, [row]} -> Row.to_task(row)
      {:ok, []} -> {:error, {:task_not_found, id}}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  The live view: non-terminal, non-hidden states, and not snoozed into the
  future.

  `nil` for `project_id` means every project (the projects column's All row);
  otherwise the view is scoped to that one.
  """
  @spec list_live(t(), integer() | nil) :: {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_live(store, project_id) do
    with {:ok, rows} <-
           query(store, @list_live_tasks, [project_filter(project_id)], "listing live tasks") do
      Row.to_tasks(rows)
    end
  end

  @doc """
  `list_live/2` plus the completed (`:done`) tasks and the hidden-by-default
  states (`:someday`), for when the list view has the completed section
  toggled on. Snoozed tasks stay out either way.
  """
  @spec list_live_with_completed(t(), integer() | nil) ::
          {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_live_with_completed(store, project_id) do
    with {:ok, rows} <-
           query(
             store,
             @list_live_with_completed_tasks,
             [project_filter(project_id)],
             "listing live tasks with completed"
           ) do
      Row.to_tasks(rows)
    end
  end

  @doc """
  Every task still in the `:inbox` state, oldest first. This feeds the triage
  view.
  """
  @spec list_inbox(t(), integer() | nil) :: {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_inbox(store, project_id) do
    with {:ok, rows} <-
           query(store, @list_inbox_tasks, [project_filter(project_id)], "listing inbox tasks") do
      Row.to_tasks(rows)
    end
  end

  @doc """
  Every task in a project, at any depth and in any state, oldest first.

  It feeds the move-to-parent picker, which needs the whole tree rather than
  the scoped live view.
  """
  @spec list_project_tasks(t(), integer()) :: {:ok, [Task.t()]} | {:error, Tend.Error.t()}
  def list_project_tasks(store, project_id) when is_integer(project_id) do
    with {:ok, rows} <-
           query(
             store,
             @list_project_tasks,
             [project_id],
             "listing tasks in project #{project_id}"
           ) do
      Row.to_tasks(rows)
    end
  end

  @doc """
  The number of tasks awaiting triage.
  """
  @spec count_inbox(t(), integer() | nil) :: {:ok, integer()} | {:error, Tend.Error.t()}
  def count_inbox(store, project_id) do
    case query(store, @count_inbox_tasks, [project_filter(project_id)], "counting inbox tasks") do
      {:ok, [[count]]} -> {:ok, count}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Per-parent sub-task done/total counts, for every task that has children.

  Done children are filtered out of the live view, so the list derives its N/M
  progress from this instead. A childless task is absent from the map rather
  than present with zeroes.
  """
  @spec child_counts(t()) :: {:ok, %{integer() => ChildCount.t()}} | {:error, Tend.Error.t()}
  def child_counts(store) do
    with {:ok, rows} <- query(store, @list_child_counts, [], "listing child counts") do
      counts =
        for [parent_id, total, done] <- rows, parent_id != nil, into: %{} do
          {parent_id, %ChildCount{done: done, total: total}}
        end

      {:ok, counts}
    end
  end

  @doc """
  Each task's agent status, keyed by task id -- what the list row renders so a
  background session's state is visible without opening the task.

  A task with a workflow run in a non-terminal state takes the run's state,
  mapped into the session vocabulary (`Tend.Workflow.RunState.session_status/1`):
  a headless run has no tmux pane for the poller to classify and its step
  sessions are `:starting` for most of their life, so the run row is the
  better signal. The one exception is a paused run, which yields to the task's
  latest session status when there is one -- during a takeover the interactive
  session's own hooks say more than "paused" does -- and reads `:idle` only
  when the task has no session at all. A task with only ended runs falls
  through to its sessions.

  The session query returns every session oldest-first and the map keeps the
  last write per task, which is the most recent one. That is cheaper to reason
  about than a correlated `MAX()` subquery and needs no tiebreak rule for two
  sessions sharing a timestamp, since the ordering already falls back to id.
  Active runs come newest-first, so the first run seen per task is the one
  that wins.
  """
  @spec session_statuses(t()) ::
          {:ok, %{integer() => SessionStatus.t()}} | {:error, Tend.Error.t()}
  def session_statuses(store) do
    with {:ok, session_rows} <-
           query(store, @list_session_statuses, [], "listing session statuses"),
         {:ok, run_rows} <- query(store, @list_active_runs, [], "listing active runs") do
      statuses =
        for [task_id, status] <- session_rows, into: %{} do
          {task_id, SessionStatus.parse(status)}
        end

      {:ok, overlay_runs(run_rows, statuses)}
    end
  end

  # -- mutators --------------------------------------------------------------

  @doc """
  Moves a task to a new workflow state. Entering `:done` stamps
  `completed_at`; entering any other state clears it.
  """
  @spec set_state(t(), integer(), State.t()) :: :ok | {:error, Tend.Error.t()}
  def set_state(store, id, state) when is_integer(id) do
    if State.valid?(state) do
      execute(
        store,
        @set_task_state,
        [State.format(state), id],
        "setting task #{id} state to #{state}"
      )
    else
      {:error, {:unknown_state, to_string(state)}}
    end
  end

  @doc """
  Assigns a priority (1 = highest .. 4) to a task; `nil` clears it.
  """
  @spec set_priority(t(), integer(), Priority.t() | nil) :: :ok | {:error, Tend.Error.t()}
  def set_priority(store, id, priority) when is_integer(id) do
    if priority == nil or Priority.valid?(priority) do
      execute(store, @set_task_priority, [priority, id], "setting task #{id} priority")
    else
      {:error, {:priority_out_of_range, priority}}
    end
  end

  @doc """
  Assigns a due date (ISO 8601, validated) to a task; `nil` clears it.
  """
  @spec set_due(t(), integer(), String.t() | nil) :: :ok | {:error, Tend.Error.t()}
  def set_due(store, id, due) when is_integer(id) do
    with {:ok, normalized} <- normalize_due(due) do
      execute(store, @set_task_due, [normalized, id], "setting task #{id} due date")
    end
  end

  @doc """
  Renames a task; the new title is trimmed and blanks rejected, the same
  validation capture uses.
  """
  @spec set_title(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def set_title(store, id, title) when is_integer(id) do
    with {:ok, normalized} <- Task.normalize_title(title) do
      execute(store, @set_task_title, [normalized, id], "setting task #{id} title")
    end
  end

  @doc """
  Replaces a task's markdown body.
  """
  @spec set_body(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def set_body(store, id, body) when is_integer(id) and is_binary(body) do
    execute(store, @set_task_body, [body, id], "setting task #{id} body")
  end

  @doc """
  Adds text to the end of a task's markdown body as a new paragraph: an empty
  body simply becomes the text, otherwise a blank line separates the existing
  body from it.

  Empty or whitespace-only text is a no-op, so callers cannot leave stray
  blank lines behind. The append itself happens in SQL, so it is atomic
  against a concurrent writer.
  """
  @spec append_body(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def append_body(store, id, text) when is_integer(id) and is_binary(text) do
    if String.trim(text) == "" do
      :ok
    else
      execute(store, @append_task_body, [text, id], "appending to task #{id} body")
    end
  end

  @doc """
  Removes a task. Its sub-tasks cascade away with it (the `parent_id` foreign
  key is `ON DELETE CASCADE`), and the `task_events` trigger logs one
  `deleted` row per task that went.

  Deleting an id that is not there is not an error, exactly as Go's is not:
  the statement matches no rows and the generated `:exec` method discards the
  row count.
  """
  @spec delete_task(t(), integer()) :: :ok | {:error, Tend.Error.t()}
  def delete_task(store, id) when is_integer(id) do
    execute(store, @delete_task, [id], "deleting task #{id}")
  end

  # -- workflow definitions --------------------------------------------------
  #
  # The workflow *rows*: a definition's name, description and step count. The
  # steps and edges themselves get their own API in a later part of the port;
  # `duplicate_workflow/3` writes both tables directly because that is what
  # Go's DuplicateWorkflow does, and it is the only function here with logic
  # worth the name.
  #
  # Nothing calls any of this yet. The MCP workflow tools and the TUI's
  # authoring view are later phases, so this is an internal API with no caller
  # -- fully tested, but dead until they arrive.

  @doc """
  Adds a workflow definition.

  The name is trimmed by `Tend.Workflow.normalize_name/1` and a blank one is
  refused with `:empty_name`. Names are unique case-insensitively -- the
  column's collation is `NOCASE` -- and a collision surfaces as the driver's
  constraint error wrapped in `{:query_failed, "creating workflow ...", _}`,
  never as a sentinel, exactly as Go lets sqlite's `UNIQUE constraint failed`
  through here and in `CreateProject`.

  The workflow comes back with `step_count: 0`: it has no steps yet, and
  nothing counted them.
  """
  @spec create_workflow(t(), String.t(), String.t()) ::
          {:ok, Workflow.t()} | {:error, Tend.Error.t()}
  def create_workflow(store, name, description) when is_binary(description) do
    with {:ok, n} <- Workflow.normalize_name(name),
         {:ok, row} <- insert_workflow(store, n, description) do
      Row.to_workflow(row, 0)
    end
  end

  @doc """
  Loads one workflow by id.

  A workflow that is not there is `{:error, :workflow_not_found}` --
  `workflow.ErrWorkflowNotFound`, which Go's `GetWorkflow` substitutes for
  `sql.ErrNoRows` so callers can match it. (`get_task/2` has to invent its
  own reason because Go has no sentinel there; here there is one to port.)
  """
  @spec get_workflow(t(), integer()) :: {:ok, Workflow.t()} | {:error, Tend.Error.t()}
  def get_workflow(store, id) when is_integer(id) do
    with {:ok, row} <- workflow_row(store, id), do: Row.to_workflow(row, 0)
  end

  @doc """
  Resolves a workflow by name, case-insensitively.

  Names resolve, never create: `tend workflow start <name>` matches on
  `:workflow_not_found` to report a typo. The name is normalized first, so a
  blank one is `:empty_name` rather than a lookup that cannot match.
  """
  @spec workflow_by_name(t(), String.t()) :: {:ok, Workflow.t()} | {:error, Tend.Error.t()}
  def workflow_by_name(store, name) do
    with {:ok, n} <- Workflow.normalize_name(name) do
      case query(store, @get_workflow_by_name, [n], "loading workflow #{quoted(n)}") do
        {:ok, [row]} -> Row.to_workflow(row, 0)
        {:ok, []} -> {:error, :workflow_not_found}
        {:error, reason} -> {:error, reason}
      end
    end
  end

  @doc """
  Every workflow, by name, each with its step count.

  The count comes from the grouped `LEFT JOIN` in the statement rather than a
  second query, so a workflow with no steps still appears -- with zero.
  """
  @spec list_workflows(t()) :: {:ok, [Workflow.t()]} | {:error, Tend.Error.t()}
  def list_workflows(store) do
    with {:ok, rows} <- query(store, @list_workflows, [], "listing workflows") do
      Row.to_workflows(rows)
    end
  end

  @doc """
  Changes a workflow's name, normalized the way `create_workflow/3` normalizes
  it -- including the duplicate, which is the same constraint error.
  """
  @spec rename_workflow(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def rename_workflow(store, id, name) when is_integer(id) do
    with {:ok, n} <- Workflow.normalize_name(name) do
      execute(store, @rename_workflow, [n, id], "renaming workflow #{id}")
    end
  end

  @doc """
  Replaces a workflow's description.
  """
  @spec set_workflow_description(t(), integer(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def set_workflow_description(store, id, description)
      when is_integer(id) and is_binary(description) do
    execute(
      store,
      @set_workflow_description,
      [description, id],
      "setting workflow #{id} description"
    )
  end

  @doc """
  Removes a workflow, its steps and edges, and the history of its runs -- the
  last three by migration 9's cascades, from the one `DELETE`. The runs' tasks
  are untouched: a run belongs to its definition, a task does not.

  Refused with `{:in_use, "workflow <id>", run_id}`, naming the run, while any
  run of it is in a non-terminal state: the runner reads the definition live at
  each step start, so pulling it out from under a live run would strand the
  run. The check and the delete share a transaction so a run created in between
  cannot slip through.

  Deleting an id that is not there is not an error, exactly as `delete_task/2`
  is not, and for the same reason.
  """
  @spec delete_workflow(t(), integer()) :: :ok | {:error, Tend.Error.t()}
  def delete_workflow(store, id) when is_integer(id) do
    transaction(store, fn store ->
      with {:ok, active} <-
             query(
               store,
               @list_active_run_ids_for_workflow,
               [id],
               "checking runs of workflow #{id}"
             ),
           :ok <- refuse_if_live(active, "workflow #{id}") do
        execute(store, @delete_workflow, [id], "deleting workflow #{id}")
      end
    end)
  end

  @doc """
  Copies a workflow under a new name: its steps with their prompts and
  settings, and its edges re-pointed at the copied steps.

  One transaction, so a copy is whole or absent. The run history is not copied,
  because it belongs to the original; the authoring TUI's "duplicate" is the
  intended caller.

  The copy's edges are the interesting part. Each copied step remembers which
  original it came from, and every edge is rewritten through that map, so an
  edge of the copy can only ever point at a step of the copy -- including the
  loop-back edges, whose `max_iterations` bound rides along.
  """
  @spec duplicate_workflow(t(), integer(), String.t()) ::
          {:ok, Workflow.t()} | {:error, Tend.Error.t()}
  def duplicate_workflow(store, id, new_name) when is_integer(id) do
    with {:ok, n} <- Workflow.normalize_name(new_name) do
      transaction(store, fn store -> copy_workflow(store, id, n) end)
    end
  end

  # -- agent sessions --------------------------------------------------------
  #
  # Nothing calls any of this yet. The `agent-hook` command that drives
  # `set_session_status/3` is Phase 2 and the sessions view that drives the
  # rest is Phase 4; this is an internal API with no caller, tested directly.

  @doc """
  Records a Claude Code session about to be launched against a task: the
  pinned external session id, the directory it will run in, and the task's
  title snapshotted as the label. `tmux_session` is the wrapping tmux
  session's name, or `""` when the session isn't launched under tmux.

  It is called right before the terminal handoff, not after it returns, so the
  row exists for the session's own hooks to find from its very first turn. The
  row starts with status `:starting` and a stamped `status_updated_at`; a
  launch that then fails is expected to take the row back with
  `delete_session/2`.

  `workflow_step_run_id` is always NULL here. The session that belongs to a
  workflow step is written by `CreateStepRunSession`, a later part of the
  store port.
  """
  @spec create_session(t(), integer(), String.t(), String.t(), String.t(), String.t()) ::
          {:ok, Session.t()} | {:error, Tend.Error.t()}
  def create_session(store, task_id, external_id, cwd, label, tmux_session)
      when is_integer(task_id) and is_binary(external_id) and is_binary(cwd) and
             is_binary(label) and is_binary(tmux_session) do
    context = "inserting session for task #{task_id}"

    case query(
           store,
           @create_session,
           [task_id, external_id, cwd, label, tmux_session, nil],
           context
         ) do
      {:ok, [row]} -> Row.to_session(row)
      {:ok, rows} -> {:error, {:query_failed, context, {:rows_returned, length(rows)}}}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Removes a session row, for the one case a row should not outlive the moment
  it was written: a launch whose handoff failed (a non-zero exit, a tmux that
  would not start) never became a session, and the row `create_session/6`
  wrote ahead of it would otherwise read as one.

  Deleting an id that is already gone is not an error.
  """
  @spec delete_session(t(), integer()) :: :ok | {:error, Tend.Error.t()}
  def delete_session(store, id) when is_integer(id) do
    execute(store, @delete_session, [id], "deleting session #{id}")
  end

  @doc """
  A task's sessions, most recently active first -- the resume picker's source
  list.
  """
  @spec list_sessions_for_task(t(), integer()) :: {:ok, [Session.t()]} | {:error, Tend.Error.t()}
  def list_sessions_for_task(store, task_id) when is_integer(task_id) do
    with {:ok, rows} <-
           query(
             store,
             @list_sessions_for_task,
             [task_id],
             "listing sessions for task #{task_id}"
           ) do
      Row.to_sessions(rows)
    end
  end

  @doc """
  Every session on every task in a project, most recently active first, each
  with its task's title and state -- the agents view's list.

  `nil` for `project_id` means all projects (the projects column's All row),
  the same convention `list_live/2` uses.
  """
  @spec list_sessions_for_project(t(), integer() | nil) ::
          {:ok, [TaskSession.t()]} | {:error, Tend.Error.t()}
  def list_sessions_for_project(store, project_id) do
    with {:ok, rows} <-
           query(
             store,
             @list_sessions_for_project,
             [project_filter(project_id)],
             "listing sessions for project"
           ) do
      Row.to_task_sessions(rows)
    end
  end

  @doc """
  Bumps a session's last-active timestamp after a resume.
  """
  @spec touch_session(t(), integer()) :: :ok | {:error, Tend.Error.t()}
  def touch_session(store, id) when is_integer(id) do
    execute(store, @touch_session, [id], "touching session #{id}")
  end

  @doc """
  Replaces a session's label with a short description of what it actually did,
  derived from the post-session recap call -- the auto-naming fix for the
  static task-title snapshot not distinguishing sessions on the same task.

  Keyed by `external_id` rather than the row id: it is the identifier the
  recap path has in hand for a freshly launched session and a resumed one
  alike.
  """
  @spec update_session_label(t(), String.t(), String.t()) :: :ok | {:error, Tend.Error.t()}
  def update_session_label(store, external_id, label)
      when is_binary(external_id) and is_binary(label) do
    execute(
      store,
      @update_session_label,
      [label, external_id],
      "updating session label for #{external_id}"
    )
  end

  @doc """
  Flags a session as still owing a recap, set when a session is backgrounded
  rather than exited so the recap call is deliberately skipped while it is
  live. The SessionEnd hook drains the flag once the session is really over.
  """
  @spec set_session_needs_recap(t(), String.t(), boolean()) :: :ok | {:error, Tend.Error.t()}
  def set_session_needs_recap(store, external_id, needs)
      when is_binary(external_id) and is_boolean(needs) do
    # Go's generated parameter is an int64 and the column is INTEGER, so the
    # boolean is widened here rather than relying on the driver's own idea of
    # what a boolean binds as.
    value = if needs, do: 1, else: 0

    execute(
      store,
      @set_session_needs_recap,
      [value, external_id],
      "setting needs_recap for #{external_id}"
    )
  end

  @doc """
  Records what a session's Claude Code hooks last reported about it, keyed by
  `external_id` -- the id the hook payload carries as `session_id`, which is
  what makes the correlation a lookup rather than a join.

  A session id with no row is not an error. Rows are written at launch, so a
  running session's hooks normally do match one, but a hook can still fire for
  a session tend has no row for -- a launch that failed and had its row
  deleted, or a `claude` started outside tend with tend's settings on hand.
  The UPDATE affects zero rows and that is the whole story.

  `last_active_at` is bumped alongside the status because a hook event is
  genuine activity -- it keeps the resume picker's newest-first ordering
  honest for a session that has been running in the background.

  Unlike `set_state/3`, a status outside the set raises rather than returning
  an error. A state name reaches `set_state/3` from a user typing it; a status
  reaches here only from the hook command's fixed event table
  (`agent.StatusForEvent`), so anything else is a bug in this tree rather than
  something a caller can hand back to a user.
  """
  @spec set_session_status(t(), String.t(), SessionStatus.t()) :: :ok | {:error, Tend.Error.t()}
  def set_session_status(store, external_id, status) when is_binary(external_id) do
    execute(
      store,
      @set_session_status,
      [SessionStatus.format(status), external_id],
      "setting status for session #{external_id}"
    )
  end

  @doc """
  Every session still owing a recap: one that was backgrounded rather than
  exited, so the recap call was deliberately skipped while it was live.

  Deliberately not filtered to `status = 'ended'`. A host that dies takes its
  tmux server and its chance to fire SessionEnd with it, and such a session
  would be stranded forever by a status filter. The caller decides liveness
  with `tmux has-session`, which is authoritative in every case -- including
  `/clear`, which fires SessionEnd while the process keeps running.
  """
  @spec list_sessions_needing_recap(t()) :: {:ok, [Session.t()]} | {:error, Tend.Error.t()}
  def list_sessions_needing_recap(store) do
    with {:ok, rows} <-
           query(store, @list_sessions_needing_recap, [], "listing sessions needing recap") do
      Row.to_sessions(rows)
    end
  end

  @doc """
  Every session tend could plausibly still poll for pane-based status:
  launched under tmux at all, and not already known to have ended -- a session
  already reporting `:ended` has nothing left to poll.
  """
  @spec sessions_with_tmux(t()) :: {:ok, [Session.t()]} | {:error, Tend.Error.t()}
  def sessions_with_tmux(store) do
    with {:ok, rows} <- query(store, @list_sessions_with_tmux, [], "listing sessions with tmux") do
      Row.to_sessions(rows)
    end
  end

  @doc """
  Atomically takes ownership of a session's owed recap, reporting whether this
  caller is the one that got it.

  The UPDATE clears `needs_recap` only if it was still set, so of two tend
  instances draining the same debt concurrently exactly one sees `true` and
  fires the (expensive, and side-effecting) recap call.

  Claiming before running the recap rather than after means a recap that then
  fails loses the debt. That is the intended trade: it bounds the work to one
  attempt instead of retrying forever, consistent with the existing convention
  that a lost automatic recap is not something the user can act on.
  """
  @spec claim_session_recap(t(), String.t()) :: {:ok, boolean()} | {:error, Tend.Error.t()}
  def claim_session_recap(store, external_id) when is_binary(external_id) do
    affected(
      store,
      @claim_session_recap,
      [external_id],
      "claiming recap for session #{external_id}"
    )
  end

  @doc """
  Writes `:working` for the capture-pane poller, but only if no hook has
  updated the session's status since `prev_status_updated_at` -- the value the
  caller read from the row right before it captured the pane.

  A hook (Stop/Notification/SessionEnd) landing in between moves
  `status_updated_at` first, so the underlying CAS UPDATE affects zero rows
  and the hook's authoritative status is left standing; the poller's guess
  never overwrites it.

  A `nil` `prev_status_updated_at` means the caller observed the column as
  NULL -- a session no hook has ever touched -- matched against SQL NULL via
  `IS` rather than a sentinel string. It is Go's zero `time.Time`.

  Reports whether the write took effect. `false` is not an error: it means the
  race was correctly lost to fresher, authoritative data, which is the whole
  point of the compare-and-swap.
  """
  @spec set_session_working_if_unchanged(t(), String.t(), DateTime.t() | nil) ::
          {:ok, boolean()} | {:error, Tend.Error.t()}
  def set_session_working_if_unchanged(store, external_id, prev_status_updated_at)
      when is_binary(external_id) do
    affected(
      store,
      @set_session_working_if_unchanged,
      [external_id, status_updated_at_param(prev_status_updated_at)],
      "setting working status for session #{external_id}"
    )
  end

  @doc """
  Takes a session back from `:working` to `:idle`, the other half of the
  poller's CAS pair alongside `set_session_working_if_unchanged/3`.

  Without this, a `:working` status the poller wrote -- whether from a genuine
  race against a Stop hook's own write, or one trailing frame of stale chrome
  -- has no way back down until the *next* hook fires, which can be an
  arbitrarily long wait. The caller only invokes this once it has already read
  `status = 'working'` itself, so this closes that gap by re-checking on every
  tick that still sees no working chrome.

  Same compare-and-swap contract as `set_session_working_if_unchanged/3`: a
  hook landing between the caller's read and this write moves
  `status_updated_at` first, so the UPDATE affects zero rows and the hook's
  own status -- idle, blocked, ended, whatever it set -- is left standing.
  """
  @spec set_session_idle_if_unchanged(t(), String.t(), DateTime.t() | nil) ::
          {:ok, boolean()} | {:error, Tend.Error.t()}
  def set_session_idle_if_unchanged(store, external_id, prev_status_updated_at)
      when is_binary(external_id) do
    affected(
      store,
      @set_session_idle_if_unchanged,
      [external_id, status_updated_at_param(prev_status_updated_at)],
      "setting idle status for session #{external_id}"
    )
  end

  @doc """
  Writes `:ended` for a session the poller has found gone via
  `tmux has-session` -- the SessionEnd hook's replacement when the host died
  before it could fire one.

  Same compare-and-swap contract as `set_session_working_if_unchanged/3`: a
  hook landing between the caller's liveness check and this write moves
  `status_updated_at` first, so the UPDATE affects zero rows and the hook's
  own status is left standing.
  """
  @spec set_session_ended_if_unchanged(t(), String.t(), DateTime.t() | nil) ::
          {:ok, boolean()} | {:error, Tend.Error.t()}
  def set_session_ended_if_unchanged(store, external_id, prev_status_updated_at)
      when is_binary(external_id) do
    affected(
      store,
      @set_session_ended_if_unchanged,
      [external_id, status_updated_at_param(prev_status_updated_at)],
      "setting ended status for session #{external_id}"
    )
  end

  # -- transactions ----------------------------------------------------------

  @doc """
  Runs `fun` inside a transaction, committing its result and rolling back on
  `{:error, reason}`.

  The port of `inTx` in `internal/store/projects.go`, and public for the same
  reason Go's is package-wide: every multi-statement invariant in the store
  goes through it. `tasks.project_id` carries no foreign key (see migration
  00007), so the writes that stand in for one have to be atomic themselves.

  Go's helper takes a `func(q *gen.Queries) error` and hands it a `Queries`
  bound to the transaction. exqlite has no such object -- a transaction is a
  property of the connection, not a handle -- so `fun` is handed the store
  itself and simply calls the ordinary functions on it.

  A raise, a throw or an exit inside `fun` rolls back and is re-raised
  unchanged, which is what Go's `defer tx.Rollback()` buys it: the store's
  connection is long-lived, so a transaction left open by an unwinding caller
  would block every later write on it.

  Nothing in the task surface is multi-statement; `delete_workflow/2` and
  `duplicate_workflow/3` are its first callers, and the rest -- `SetProject`,
  `SetParent`, `SetTags`, `DeleteProject` -- are later parts of the store port.
  """
  @spec transaction(t(), (t() -> result)) :: result | {:error, Tend.Error.t()} when result: var
  def transaction(%__MODULE__{} = store, fun) when is_function(fun, 1) do
    with :ok <- statement(store, "BEGIN", "beginning transaction") do
      try do
        case fun.(store) do
          {:error, reason} ->
            rollback(store)
            {:error, reason}

          result ->
            case statement(store, "COMMIT", "committing transaction") do
              :ok -> result
              {:error, reason} -> {:error, rollback_and(store, reason)}
            end
        end
      catch
        kind, reason ->
          rollback(store)
          :erlang.raise(kind, reason, __STACKTRACE__)
      end
    end
  end

  defp ensure_directory(path) do
    case path |> Path.dirname() |> File.mkdir_p() do
      :ok -> :ok
      {:error, reason} -> {:error, {:db_directory_failed, Path.dirname(path), reason}}
    end
  end

  defp connect(path) do
    case Sqlite3.open(path) do
      {:ok, conn} -> {:ok, conn}
      {:error, reason} -> {:error, {:db_open_failed, path, reason}}
    end
  end

  defp pragmas(conn) do
    Enum.reduce_while(
      [
        "PRAGMA journal_mode = WAL",
        "PRAGMA busy_timeout = 5000",
        "PRAGMA foreign_keys = ON"
      ],
      :ok,
      fn sql, :ok ->
        case Sqlite3.execute(conn, sql) do
          :ok -> {:cont, :ok}
          {:error, reason} -> {:halt, {:error, {:pragma_failed, sql, reason}}}
        end
      end
    )
  end

  # The port of Go's projectFilter. sqlc's nullable named argument becomes an
  # untyped interface{} there, so nil means "every project" and a bare int64
  # scopes the query; exqlite binds nil as SQL NULL and an integer as itself,
  # which is the same two cases against the same `?1 IS NULL OR ...` clause.
  # The guard is the point: without it a project id of the wrong shape would
  # bind as something `?1 IS NULL` reads as present, quietly scoping the query
  # to nothing rather than failing.
  defp project_filter(nil), do: nil
  defp project_filter(id) when is_integer(id), do: id

  defp insert_task(store, sql, params) do
    with {:ok, row} <- insert_one(store, sql, params, "inserting task"), do: Row.to_task(row)
  end

  # `INSERT ... RETURNING` yields exactly one row. Anything else means the
  # statement above stopped being the insert it is copied from, which is worth
  # an error rather than a match failure three frames away.
  defp insert_one(store, sql, params, context) do
    case query(store, sql, params, context) do
      {:ok, [row]} -> {:ok, row}
      {:ok, rows} -> {:error, {:query_failed, context, {:rows_returned, length(rows)}}}
      {:error, reason} -> {:error, reason}
    end
  end

  defp normalize_due(nil), do: {:ok, nil}
  defp normalize_due(due) when is_binary(due), do: Task.normalize_date(due)

  # -- the workflow helpers --------------------------------------------------

  defp insert_workflow(store, name, description) do
    insert_one(store, @create_workflow, [name, description], "creating workflow #{quoted(name)}")
  end

  # The raw `workflows` row, or the sentinel Go substitutes for sql.ErrNoRows.
  # Shared by get_workflow/2 and the duplicate, which wants the description off
  # the row rather than a domain value.
  defp workflow_row(store, id) do
    case query(store, @get_workflow, [id], "loading workflow #{id}") do
      {:ok, [row]} -> {:ok, row}
      {:ok, []} -> {:error, :workflow_not_found}
      {:error, reason} -> {:error, reason}
    end
  end

  # Go's `if len(active) > 0 { return workflow.InUseError(..., active[0]) }`.
  # The statement orders by id, so the run named is the oldest live one, the
  # same one Go names.
  defp refuse_if_live([], _what), do: :ok
  defp refuse_if_live([[run_id] | _rest], what), do: {:error, Workflow.in_use_error(what, run_id)}

  # The body of duplicate_workflow/3, inside the transaction.
  defp copy_workflow(store, id, name) do
    with {:ok, [_id, _name, description, _created, _updated]} <- workflow_row(store, id),
         {:ok, [copy_id | _rest] = copy} <- insert_workflow(store, name, description),
         {:ok, steps} <- query(store, @list_steps, [id], "listing steps of workflow #{id}"),
         {:ok, step_ids} <- copy_steps(store, copy_id, steps),
         {:ok, edges} <-
           query(store, @list_edges_for_workflow, [id], "listing edges of workflow #{id}"),
         :ok <- copy_edges(store, step_ids, edges) do
      Row.to_workflow(copy, length(steps))
    end
  end

  # Copies each step wholesale -- sort order included, so the copy lists in the
  # original's authoring order -- and returns the old id => new id map the
  # edges are re-pointed through.
  defp copy_steps(store, workflow_id, steps) do
    Enum.reduce_while(steps, {:ok, %{}}, fn step, {:ok, step_ids} ->
      [id, _workflow_id, name, kind, prompt_md, model, permission_mode, sort_order | _stamps] =
        step

      params = [workflow_id, name, kind, prompt_md, model, permission_mode, sort_order]

      case insert_one(store, @create_step_full, params, "copying step #{id}") do
        {:ok, [copied | _rest]} -> {:cont, {:ok, Map.put(step_ids, id, copied)}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
  end

  # Every edge of the original, with both endpoints translated. `Map.fetch!`
  # rather than Go's `idMap[e.FromStepID]`, whose miss would be a silent zero:
  # the listing joins on `from_step_id`, and `SetEdge` refuses an edge whose
  # ends are in different workflows, so both endpoints are always in the map --
  # and if that ever stops being true this should say so rather than write an
  # edge pointing at nothing.
  defp copy_edges(store, step_ids, edges) do
    Enum.reduce_while(edges, :ok, fn edge, :ok ->
      [id, from_step_id, outcome, to_step_id, max_iterations] = edge

      params = [
        Map.fetch!(step_ids, from_step_id),
        outcome,
        Map.fetch!(step_ids, to_step_id),
        max_iterations
      ]

      case insert_one(store, @upsert_edge, params, "copying edge #{id}") do
        {:ok, _row} -> {:cont, :ok}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
  end

  # Go's %q on a name, for the call-site labels that carry one.
  defp quoted(name), do: Tend.Error.quote_go(name)

  # Best effort, exactly as Go's `defer func() { _ = tx.Rollback() }()` is: the
  # caller is already getting the real failure, and a rollback that itself
  # fails has nothing better to say. After a successful COMMIT it is a no-op
  # error ("cannot rollback - no transaction is active"), which is why the
  # result is discarded rather than reported.
  defp rollback(store) do
    _ = statement(store, "ROLLBACK", "rolling back transaction")
    :ok
  end

  defp rollback_and(store, reason) do
    rollback(store)
    reason
  end

  # The second half of SessionStatuses: the active runs, newest-first, laid
  # over the per-task session statuses. `seen` is Go's `fromRun` map.
  defp overlay_runs(rows, statuses) do
    {statuses, _seen} = Enum.reduce(rows, {statuses, MapSet.new()}, &overlay_run/2)
    statuses
  end

  # Go reads r.State off a gen.WorkflowRun as a raw string and hands it to
  # workflow.RunState(r.State).SessionStatus(), which answers for any value.
  # RunState.parse/1 is strict, so a state the schema's CHECK does not allow
  # lands on the same "says nothing" answer a terminal one does -- and, like a
  # terminal one, does not claim the task either, so an older active run still
  # gets its turn.
  defp overlay_run(row, {statuses, seen} = unchanged) do
    [_id, _workflow_id, task_id, _cwd, state | _rest] = row

    with false <- MapSet.member?(seen, task_id),
         {:ok, run_state} <- RunState.parse(state),
         {:ok, status} <- RunState.session_status(run_state) do
      # A paused run claims the task either way, but yields its own status to
      # the task's session when there is one: during a takeover the
      # interactive session's hooks say more than "paused" does.
      if run_state == :paused and Map.has_key?(statuses, task_id) do
        {statuses, MapSet.put(seen, task_id)}
      else
        {Map.put(statuses, task_id, status), MapSet.put(seen, task_id)}
      end
    else
      # Already spoken for by a newer run, or a run whose state has no status.
      _skip -> unchanged
    end
  end

  # The port of Go's statusUpdatedAtParam: a session's status_updated_at back
  # in the form the CAS queries compare against. nil is Go's zero time -- the
  # caller observed the column as NULL, a session no hook has ever touched --
  # and binds as SQL NULL, matched by the queries' `IS` rather than by a
  # sentinel string. Everything else is rendered at exactly the three
  # fractional digits SQLite wrote (see Tend.Store.Row.format_status_time/1).
  defp status_updated_at_param(nil), do: nil
  defp status_updated_at_param(%DateTime{} = at), do: Row.format_status_time(at)

  # Runs a statement for effect. Go's generated :exec methods discard the
  # sql.Result, and so does this: not one caller in the task surface looks at
  # the row count.
  defp execute(store, sql, params, context) do
    with {:ok, _rows} <- query(store, sql, params, context), do: :ok
  end

  # The port of sqlc's `:execrows` methods, which return RowsAffected: the
  # compare-and-swaps report whether they won, so the row count is the answer
  # rather than something to discard. sqlite3_changes counts the rows the most
  # recent statement on *this connection* changed, which is why the read has
  # to sit directly after the statement -- and why it is only sound for a
  # table with no triggers on it, as agent_sessions has none.
  defp affected(%__MODULE__{conn: conn} = store, sql, params, context) do
    with {:ok, _rows} <- query(store, sql, params, context) do
      case Sqlite3.changes(conn) do
        {:ok, count} -> {:ok, count > 0}
        {:error, reason} -> {:error, {:query_failed, context, reason}}
      end
    end
  end

  # Prepare, bind, run, release. The statement is released on both paths --
  # exqlite hands back a NIF resource, and leaking one holds the compiled
  # statement (and its read transaction) open.
  defp query(%__MODULE__{conn: conn}, sql, params, context) do
    case Sqlite3.prepare(conn, sql) do
      {:ok, statement} ->
        result =
          with :ok <- Sqlite3.bind(statement, params) do
            Sqlite3.fetch_all(conn, statement)
          end

        Sqlite3.release(conn, statement)
        tag(result, context)

      {:error, reason} ->
        {:error, {:query_failed, context, reason}}
    end
  end

  # BEGIN/COMMIT/ROLLBACK take no parameters and return no rows, so they go
  # through sqlite3_exec the way the migrator's statements do.
  defp statement(%__MODULE__{conn: conn}, sql, context) do
    case Sqlite3.execute(conn, sql) do
      :ok -> :ok
      {:error, reason} -> {:error, {:query_failed, context, reason}}
    end
  end

  # Every driver failure is wrapped with the label its Go call site passes to
  # fmt.Errorf, so the two trees' messages read the same.
  defp tag({:ok, rows}, _context), do: {:ok, rows}
  defp tag({:error, reason}, context), do: {:error, {:query_failed, context, reason}}
end
