defmodule Tend.Task.BriefTest do
  use ExUnit.Case, async: true

  alias Tend.Task
  alias Tend.Task.BlockerCount
  alias Tend.Task.Brief
  alias Tend.Task.LogEntry
  alias Tend.Task.Project

  # Go's tests write their timestamps in time.Local and expect the dates and
  # stamps to come back in the same zone. Timestamps are stored UTC, so the
  # instant a local wall clock names is what a task carries -- computed here
  # without going through the conversion the module under test uses, so the two
  # have to agree without either hard-coding an offset.
  defp local(year, month, day, hour, minute) do
    [utc | _ambiguous] =
      :calendar.local_time_to_universal_time_dst({{year, month, day}, {hour, minute, 0}})

    utc |> NaiveDateTime.from_erl!() |> DateTime.from_naive!("Etc/UTC")
  end

  # The brief the golden below was generated from, by running the Go
  # SessionSystemPrompt over the same values. Local wall clocks, so the dates
  # it renders are the same in every zone the suite runs in.
  defp golden_brief do
    created = local(2026, 9, 1, 12, 0)
    updated = local(2026, 9, 2, 12, 0)
    logged = local(2026, 9, 3, 9, 30)

    %Brief{
      task: %Task{
        id: 42,
        title: ~S(Ship the "thing"),
        body_md: "## Plan\n\nDo it carefully.\n",
        state: :doing,
        parent_id: 7,
        project_id: 3,
        priority: 1,
        due: "2026-09-20",
        snooze_until: "2026-09-15",
        created_at: created,
        updated_at: updated,
        completed_at: updated
      },
      project: %Project{id: 3, name: "tend", cwd: "/Users/me/code/tend"},
      tags: ["cli", "urgent"],
      parent: %Task{id: 7, title: "Epic", state: :todo},
      children: [
        %Task{id: 43, title: "first", state: :done},
        %Task{id: 44, title: "second", state: :review}
      ],
      child_blockers: %{44 => %BlockerCount{open: 1, total: 1}},
      blockers: [
        %Task{id: 10, title: "prereq", state: :todo},
        %Task{id: 11, title: "landed", state: :done}
      ],
      blocking: [%Task{id: 50, title: "follow-up", state: :todo}],
      log: [%LogEntry{body: "  Wired the flag.  ", created_at: logged}]
    }
  end

  # Verbatim output of the Go `SessionSystemPrompt` for the brief above --
  # every section, in order, with the separators it emits. Regenerated by
  # running brief.go over the same values; a diff here is a port bug.
  @golden ~S"""
  This Claude Code session was launched from tend, a terminal task tracker, and is bound to tend task #42: "Ship the \"thing\"". The task is laid out below; treat it as the context for this session and do not ask the user to restate it. The details are a snapshot from when the session started. The tend MCP tools (mcp__tend__get_current_task, mcp__tend__list_subtasks, mcp__tend__append_task_body, mcp__tend__set_task_state, mcp__tend__create_subtask, ...) read and change the live task; record progress and decisions by appending to the task body, since log entries are the user's.

  ## Task #42: Ship the "thing"

  - State: doing
  - Project: tend (default cwd /Users/me/code/tend)
  - Priority: A
  - Due: 2026-09-20
  - Snoozed until: 2026-09-15
  - Tags: cli, urgent
  - Created: 2026-09-01
  - Updated: 2026-09-02
  - Completed: 2026-09-02
  - Parent task: #7 "Epic" (todo)

  ### Sub-tasks (1 of 2 done)

  - [x] #43 "first" (done)
  - [ ] #44 "second" (in review), waiting on 1 open task(s)

  ### Blocked by (1 open)

  - [ ] #10 "prereq" (todo)
  - [x] #11 "landed" (done)

  ### Blocks

  - #50 "follow-up" (todo)

  ### Description

  ## Plan

  Do it carefully.

  ### Log (newest first)

  - 2026-09-03 09:30: Wired the flag.
  """

  # The same, for a task with nothing but a title and a state.
  @golden_bare ~S"""
  This Claude Code session was launched from tend, a terminal task tracker, and is bound to tend task #1: "Lone". The task is laid out below; treat it as the context for this session and do not ask the user to restate it. The details are a snapshot from when the session started. The tend MCP tools (mcp__tend__get_current_task, mcp__tend__list_subtasks, mcp__tend__append_task_body, mcp__tend__set_task_state, mcp__tend__create_subtask, ...) read and change the live task; record progress and decisions by appending to the task body, since log entries are the user's.

  ## Task #1: Lone

  - State: inbox
  - Parent task: none (a top-level task)

  ### Description

  (no description)
  """

  describe "the struct" do
    test "a bare brief defaults to Go's zero values" do
      assert %Brief{} == %Brief{
               task: %Task{},
               project: %Project{},
               tags: [],
               parent: nil,
               children: [],
               child_blockers: %{},
               blockers: [],
               blocking: [],
               log: []
             }
    end
  end

  describe "render/1 against the Go output" do
    test "a full brief is byte for byte what SessionSystemPrompt produces" do
      assert Brief.render(golden_brief()) == @golden
    end

    test "a bare task is byte for byte what SessionSystemPrompt produces" do
      brief = %Brief{task: %Task{id: 1, title: "Lone", state: :inbox}}

      assert Brief.render(brief) == @golden_bare
    end
  end

  describe "render/1" do
    # The full brief lays every section out: facts, parent, sub-tasks with
    # blocked markers, both dependency directions, the body, and the log.
    test "lays out every section" do
      created = local(2026, 9, 1, 12, 0)

      brief = %Brief{
        task: %Task{
          id: 42,
          title: "Ship the thing",
          body_md: "## Plan\n\nDo it carefully.\n",
          state: :doing,
          parent_id: 7,
          project_id: 3,
          priority: 1,
          due: "2026-09-20",
          created_at: created,
          updated_at: DateTime.add(created, 24, :hour)
        },
        project: %Project{id: 3, name: "tend", cwd: "/Users/me/code/tend"},
        tags: ["cli", "urgent"],
        parent: %Task{id: 7, title: "Epic", state: :todo},
        children: [
          %Task{id: 43, title: "first", state: :done},
          %Task{id: 44, title: "second", state: :todo}
        ],
        child_blockers: %{44 => %BlockerCount{open: 1, total: 1}},
        blockers: [
          %Task{id: 10, title: "prereq", state: :todo},
          %Task{id: 11, title: "landed", state: :done}
        ],
        blocking: [%Task{id: 50, title: "follow-up", state: :todo}],
        log: [%LogEntry{body: "Wired the flag.", created_at: DateTime.add(created, 48, :hour)}]
      }

      got = Brief.render(brief)

      for want <- [
            ~S|bound to tend task #42: "Ship the thing"|,
            "mcp__tend__get_current_task",
            "## Task #42: Ship the thing",
            "- State: doing",
            "- Project: tend (default cwd /Users/me/code/tend)",
            "- Priority: A",
            "- Due: 2026-09-20",
            "- Tags: cli, urgent",
            "- Created: 2026-09-01",
            ~S|- Parent task: #7 "Epic" (todo)|,
            "### Sub-tasks (1 of 2 done)",
            ~S|- [x] #43 "first" (done)|,
            ~S|- [ ] #44 "second" (todo), waiting on 1 open task(s)|,
            "### Blocked by (1 open)",
            ~S|- [ ] #10 "prereq" (todo)|,
            ~S|- [x] #11 "landed" (done)|,
            "### Blocks",
            ~S|- #50 "follow-up" (todo)|,
            "### Description\n\n## Plan\n\nDo it carefully.\n",
            "### Log (newest first)",
            ": Wired the flag."
          ] do
        assert String.contains?(got, want), "prompt missing #{inspect(want)}\n---\n#{got}"
      end
    end

    # A bare task renders the facts and description only: no empty sub-task,
    # dependency or log sections, and a parent line that says there is none.
    test "a bare task renders the facts and description only" do
      got = Brief.render(%Brief{task: %Task{id: 1, title: "Lone", state: :inbox}})

      for want <- [
            "## Task #1: Lone",
            "- State: inbox",
            "- Parent task: none (a top-level task)",
            "### Description\n\n(no description)\n"
          ] do
        assert String.contains?(got, want), "prompt missing #{inspect(want)}\n---\n#{got}"
      end

      for absent <- [
            "### Sub-tasks",
            "### Blocked by",
            "### Blocks",
            "### Log",
            "- Project:",
            "- Priority:",
            "- Due:",
            "- Tags:",
            "- Created:"
          ] do
        refute String.contains?(got, absent),
               "prompt has #{inspect(absent)} for a bare task\n---\n#{got}"
      end
    end

    # review is the one state whose label differs from its stored name; the
    # brief uses the label, as the UI does.
    test "uses the state's label" do
      got = Brief.render(%Brief{task: %Task{id: 1, title: "x", state: :review}})

      assert String.contains?(got, "- State: in review\n")
    end

    # A parent id with no loaded parent still names the parent by id, so a
    # failed parent lookup degrades to less detail rather than a wrong claim.
    test "names a parent by id when the parent itself was not loaded" do
      brief = %Brief{task: %Task{id: 2, title: "child", state: :todo, parent_id: 9}}

      assert String.contains?(Brief.render(brief), "- Parent task: #9\n")
    end

    # The log is capped to the most recent entries, newest first as the store
    # lists them, and the heading says how many were dropped.
    test "caps the log and says how many entries were dropped" do
      now = local(2026, 9, 3, 9, 30)
      limit = Brief.log_limit()

      log =
        for i <- 0..(limit + 4) do
          %LogEntry{body: "entry #{i}", created_at: DateTime.add(now, -i, :hour)}
        end

      got = Brief.render(%Brief{task: %Task{id: 1, title: "x", state: :todo}, log: log})

      assert String.contains?(
               got,
               "### Log (newest first; the #{limit} most recent of #{limit + 5} entries)"
             )

      assert String.contains?(got, ": entry 0\n"), "prompt dropped the newest entry\n---\n#{got}"

      refute String.contains?(got, ": entry #{limit}\n"),
             "prompt kept an entry past the cap\n---\n#{got}"
    end

    test "a log at the cap keeps the plain heading" do
      now = local(2026, 9, 3, 9, 30)

      log =
        for i <- 0..(Brief.log_limit() - 1) do
          %LogEntry{body: "entry #{i}", created_at: DateTime.add(now, -i, :hour)}
        end

      got = Brief.render(%Brief{task: %Task{id: 1, title: "x", state: :todo}, log: log})

      assert String.contains?(got, "### Log (newest first)\n\n")
      assert String.contains?(got, ": entry #{Brief.log_limit() - 1}\n")
    end

    test "a project with no default cwd renders the name alone" do
      brief = %Brief{
        task: %Task{id: 1, title: "x", state: :todo},
        project: %Project{id: 2, name: "tend"}
      }

      assert String.contains?(Brief.render(brief), "- Project: tend\n")
    end

    test "a sub-task with a blocker count of zero open is not marked as waiting" do
      brief = %Brief{
        task: %Task{id: 1, title: "x", state: :todo},
        children: [%Task{id: 2, title: "sub", state: :todo}],
        child_blockers: %{2 => %BlockerCount{open: 0, total: 1}}
      }

      got = Brief.render(brief)

      assert String.contains?(got, ~S|- [ ] #2 "sub" (todo)| <> "\n")
      refute String.contains?(got, "waiting on")
    end

    test "titles are quoted the way Go's %q quotes them" do
      brief = %Brief{
        task: %Task{id: 1, title: "x", state: :todo},
        blocking: [%Task{id: 2, title: "a \"quoted\" \\ and\ttab", state: :todo}]
      }

      assert String.contains?(
               Brief.render(brief),
               ~S|- #2 "a \"quoted\" \\ and\ttab" (todo)| <> "\n"
             )
    end

    # %q is `strconv.Quote`, not "escape the control characters": a rune that
    # is unprintable by Unicode's rules is \uNNNN, one past U+FFFF is \UNNNNNNNN,
    # and a byte that is not valid UTF-8 at all is \xNN on its own -- with the
    # rest of the title still following it, not truncated at it. Verified
    # against Go's %q over the same strings.
    test "titles Go escapes past the control characters are escaped, not passed through or truncated" do
      for {title, quoted} <- [
            {"x" <> <<0xFF>> <> "y", ~S|"x\xffy"|},
            {"a\u{A0}b", ~S|"a\u00a0b"|},
            {"\u{FEFF}head", ~S|"\ufeffhead"|},
            {"soft\u{AD}hyphen", ~S|"soft\u00adhyphen"|},
            {"note \u{1D173}", ~S|"note \U0001d173"|},
            {"café", ~S|"café"|}
          ] do
        brief = %Brief{
          task: %Task{id: 1, title: "x", state: :todo},
          blocking: [%Task{id: 2, title: title, state: :todo}]
        }

        assert String.contains?(Brief.render(brief), "- #2 #{quoted} (todo)\n"),
               "title #{inspect(title)} did not render as #{quoted}"
      end
    end

    # The preamble quotes the task's own title with the same verb, so an
    # invalid byte there must not swallow the rest of the title either.
    test "an invalid UTF-8 byte in the task's own title is escaped, not truncated" do
      got = Brief.render(%Brief{task: %Task{id: 1, title: "x" <> <<0xFF>> <> "y", state: :todo}})

      assert String.contains?(got, ~S|bound to tend task #1: "x\xffy".|)
    end

    # `%LogEntry{}`'s default `created_at` is nil, so an entry built by hand
    # reaches the stamp with no instant. Blank the stamp and keep the note
    # rather than taking the whole brief down, the way `state_label/1` blanks a
    # missing state.
    test "a log entry with no timestamp renders a blank stamp rather than raising" do
      brief = %Brief{
        task: %Task{id: 1, title: "x", state: :todo},
        log: [%LogEntry{body: "note"}]
      }

      assert String.contains?(Brief.render(brief), "- : note\n")
    end

    test "a body of nothing but whitespace reads as no description" do
      brief = %Brief{task: %Task{id: 1, title: "x", state: :todo, body_md: "   \n\n  "}}

      assert String.contains?(Brief.render(brief), "### Description\n\n(no description)\n")
    end
  end
end
