package agent

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// tmuxBinary is the tmux executable name, resolved via $PATH.
const tmuxBinary = "tmux"

// SocketName is the dedicated tmux server tend talks to, via `tmux -L`.
// A separate server is not just hygiene — it's load-bearing for the case
// where tend itself was started from inside the user's own tmux.
// tmux's "sessions should be nested with care" guard is per-server: it
// compares the attaching client's tty against that server's own panes,
// so attaching to a *different* socket never trips it. Verified against
// tmux 3.7b (docs/agent-sessions-plan.md §8.1). It also keeps tend's
// sessions out of the user's `tmux ls` and leaves their prefix, config,
// and plugins untouched.
const SocketName = "tend"

// sessionPrefix namespaces tend's tmux sessions. The full name is this
// plus the claude external session id — not the agent_sessions row id
// the plan first proposed, because no row exists at launch time
// (CreateSession runs when the terminal handoff *returns*). The UUID is
// already in hand before launch, is shell-safe, and is what Claude Code
// reports as session_id in its hook payloads, which makes Phase 4.2's
// correlation a direct lookup.
const sessionPrefix = "tend-"

// SessionName is the tmux session name wrapping a given claude session.
func SessionName(externalID string) string {
	return sessionPrefix + externalID
}

// TmuxInstalled reports whether tmux is on $PATH. Unlike CheckInstalled
// for claude, a missing tmux is not an error: launch and resume both
// fall back to handing the terminal straight to claude, exactly as they
// did before §8.1. Only backgrounding and cross-instance reconnect are
// lost.
func TmuxInstalled() bool {
	_, err := exec.LookPath(tmuxBinary)
	return err == nil
}

// tmuxConf is the generated config for tend's tmux server. It is
// deliberately minimal and single-purpose: attach, detach, scroll.
//
// Two lines are load-bearing and easy to mistake for boilerplate:
//
//   - `unbind -a -T prefix` — setting `prefix` does NOT clear tmux's
//     default key table. Left intact, and with the status bar off, a
//     stray `C-Space c` would silently create a second window with no
//     visible indication it exists, stranding the user in what looks
//     like a broken claude.
//   - `escape-time 10` — esc is Claude Code's interrupt key. tmux's
//     default escape-time makes esc-to-interrupt feel broken through
//     the extra layer, which would be the most-noticed regression of
//     wrapping claude in tmux at all.
//
// C-h is bound bare (no prefix) as the one-key background action.
// It does not capture Backspace: tmux parses 0x08 as C-h and 0x7F as
// BSpace into separate key-table entries, verified by injecting raw
// bytes into a pty against tmux 3.7b. The only setup where that would
// bite is a terminal whose Backspace sends 0x08 (terminfo kbs=^H).
const tmuxConf = `# Generated by tend — do not edit; rewritten on launch.
# See docs/agent-sessions-plan.md §8.1.

# Start from nothing so no default binding can surprise a user who has
# no status bar to see the result.
unbind -a -T prefix
set -g prefix C-Space
bind C-Space send-prefix
bind d detach-client
bind [ copy-mode
bind ? list-keys

# One-key background, no prefix. Does not shadow Backspace (0x7F).
bind -n C-h detach-client

# esc is Claude Code's interrupt key; the default delay makes it feel dead.
set -sg escape-time 10

# Look exactly like claude running directly.
set -g status off
set -g detach-on-destroy on

# Preserve what nesting otherwise degrades: truecolor and OSC 52 copy.
set -g default-terminal "tmux-256color"
set -sa terminal-features ",*:RGB"
set -g set-clipboard on

# Size to the attached client, not the smallest session member — matters
# when a second tend attaches from a different-sized terminal.
set -g aggressive-resize on
`

// ConfigPath returns where tend's generated tmux config lives:
// $XDG_CONFIG_HOME/tend/tmux.conf, falling back to ~/.config. A stable
// path rather than a temp file, because tmux reads `-f` only when the
// server *starts* — a config that vanished after the first launch would
// leave later servers unconfigured, and a real path is inspectable when
// something looks wrong.
func ConfigPath() (string, error) {
	dir := os.Getenv("XDG_CONFIG_HOME")
	if dir == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("locating tmux config dir: %w", err)
		}
		dir = filepath.Join(home, ".config")
	}
	return filepath.Join(dir, "tend", "tmux.conf"), nil
}

// WriteConfig writes tmuxConf to ConfigPath, creating the directory if
// needed, and returns the path.
//
// Note this only takes effect for servers started *after* it runs: tmux
// reads `-f` at server start and never re-reads it. Iterating on
// tmuxConf therefore needs a `tmux -L tend kill-server` to see changes,
// which is why the file is regenerated unconditionally rather than
// written once — at least the on-disk copy always matches the binary.
func WriteConfig() (string, error) {
	path, err := ConfigPath()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("creating tmux config dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(tmuxConf), 0o644); err != nil {
		return "", fmt.Errorf("writing tmux config: %w", err)
	}
	return path, nil
}

// serverArgs is the socket+config preamble every tmux invocation shares.
func serverArgs(configPath string) []string {
	return []string{"-L", SocketName, "-f", configPath}
}

// WrapTmux rewrites a direct claude command into one that runs it inside
// a named tmux session on tend's dedicated server, attached — so the
// first run is indistinguishable from handing the terminal straight to
// claude, except that detaching leaves claude running underneath.
//
// The inner command's argv is passed after `--` so tmux execs it
// directly rather than through a shell, keeping the exact argument
// boundaries LaunchCmd/ResumeCmd built (labels and prompts contain
// spaces). Env is carried over from the inner command so a caller that
// customized it isn't silently dropped.
func WrapTmux(inner *exec.Cmd, sessionName, configPath string) *exec.Cmd {
	args := serverArgs(configPath)
	args = append(args, "new-session", "-s", sessionName)
	if inner.Dir != "" {
		args = append(args, "-c", inner.Dir)
	}
	args = append(args, "--")
	args = append(args, inner.Args...)

	c := exec.Command(tmuxBinary, args...)
	c.Dir = inner.Dir
	c.Env = inner.Env
	return c
}

// AttachCmd builds the command to reattach to a tmux session that's
// already running — the cross-instance reconnect path.
//
// `-d` detaches any other client first, so a second tend instance takes
// the session over rather than mirroring it. Two clients on one session
// share a view sized to the smaller terminal, which reads as a rendering
// bug rather than a feature; taking over is what "reconnect from another
// tend" is actually asking for.
func AttachCmd(sessionName, configPath string) *exec.Cmd {
	args := append(serverArgs(configPath), "attach-session", "-d", "-t", sessionName)
	return exec.Command(tmuxBinary, args...)
}

// HasSession reports whether a tmux session of that name is currently
// alive on tend's server. This is the authoritative answer to "is the
// session still running" — the stored status is only ever a cached
// convenience. A missing tmux, a dead server, or an unknown name all
// report false, which is the correct answer in every case.
func HasSession(sessionName, configPath string) bool {
	if sessionName == "" || !TmuxInstalled() {
		return false
	}
	args := append(serverArgs(configPath), "has-session", "-t", "="+sessionName)
	return exec.Command(tmuxBinary, args...).Run() == nil
}

// KillSession terminates a live tmux session, used to clean up after a
// launch that failed inside tmux. Errors are returned but generally
// ignorable — a session that isn't there is already in the desired
// state.
func KillSession(sessionName, configPath string) error {
	args := append(serverArgs(configPath), "kill-session", "-t", "="+sessionName)
	if out, err := exec.Command(tmuxBinary, args...).CombinedOutput(); err != nil {
		return fmt.Errorf("killing tmux session %s: %s", sessionName, strings.TrimSpace(string(out)))
	}
	return nil
}

// CapturePane returns the visible contents of a live tmux session's pane,
// the raw material §8.3's classifyPane pattern-matches against to detect
// the one status no Claude Code hook can report: a session mid-tool-call.
// `-p` prints to stdout instead of a tmux buffer.
//
// No -S/-E: tmux's own default for capture-pane with neither flag is "the
// visible contents of the pane", which is exactly the on-screen chrome
// classifyPane needs. §8.3's original design sketch called for `-S -5` to
// grab "the tail", but that reads tmux's line numbering backwards —
// verified against tmux 3.7b's own man page: "zero is the first line of
// the visible pane and negative numbers are lines in the history", so
// `-S -5` starts 5 lines *above the top* of the screen, not 5 lines above
// the bottom, and with no -E the capture still runs to the bottom of the
// pane regardless. Confirmed by direct probe: `-S -5` and `-S -20`
// produced byte-identical output (the whole visible pane, history_size
// 0), while `-S -5 -E -1` produced nothing — an empty range under the
// same numbering. Omitting -S/-E entirely gives the correct "just what's
// on screen" capture with no history at all.
//
// Errors are swallowed to "" rather than returned to the caller's flow —
// a poller tick that can't read a pane just skips that session until the
// next tick, the same degrade-quietly convention HasSession and
// CapturePane's other tmux siblings already follow.
//
// No "=" prefix on -t, unlike HasSession/KillSession. Those target a
// *session* (target-session), where "=" forces an exact-string match
// instead of tmux's fnmatch-style prefix matching. capture-pane's -t
// takes a *pane* (target-pane); tmux resolves a bare session name to
// that session's active pane, but "=exact-name" is not accepted the same
// way for a pane target — verified by direct probe against tmux 3.7b:
// `-t "=tend-<id>"` fails with "can't find pane" on a session that is
// unquestionably alive (has-session with the same "=<id>" target
// succeeds against it), while `-t "tend-<id>"` (no "=") succeeds and
// returns the expected chrome. Caught live: the poller was silently
// no-op-ing on every tick with the "=" form, since CapturePane's own
// convention is to swallow the resulting exec error to "" rather than
// surface it, and no test exercised a real tmux server to catch it.
func CapturePane(sessionName, configPath string) (string, error) {
	if sessionName == "" || !TmuxInstalled() {
		return "", nil
	}
	args := append(serverArgs(configPath), "capture-pane", "-t", sessionName, "-p")
	out, err := exec.Command(tmuxBinary, args...).Output()
	if err != nil {
		return "", nil
	}
	return string(out), nil
}
